// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inference_top_D_CNN_Pipeline_loop_for_3_channel_pad_2_loop_for_channel_pad_2_loop_for_weight_p (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        OutPadConv2_V_address0,
        OutPadConv2_V_ce0,
        OutPadConv2_V_we0,
        OutPadConv2_V_d0,
        upsample_V_address0,
        upsample_V_ce0,
        upsample_V_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] OutPadConv2_V_address0;
output   OutPadConv2_V_ce0;
output   OutPadConv2_V_we0;
output  [15:0] OutPadConv2_V_d0;
output  [12:0] upsample_V_address0;
output   upsample_V_ce0;
input  [15:0] upsample_V_q0;

reg ap_idle;
reg OutPadConv2_V_ce0;
reg OutPadConv2_V_we0;
reg upsample_V_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln78_fu_151_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] c_2_reg_626;
reg   [3:0] c_2_reg_626_pp0_iter1_reg;
reg   [0:0] icmp_ln78_reg_631;
reg   [0:0] icmp_ln78_reg_631_pp0_iter1_reg;
wire   [0:0] icmp_ln80_fu_166_p2;
reg   [0:0] icmp_ln80_reg_635;
reg   [0:0] icmp_ln80_reg_635_pp0_iter1_reg;
reg   [0:0] icmp_ln80_reg_635_pp0_iter2_reg;
wire   [3:0] add_ln78_1_fu_172_p2;
reg   [3:0] add_ln78_1_reg_646;
reg   [3:0] add_ln78_1_reg_646_pp0_iter1_reg;
wire   [10:0] empty_fu_267_p2;
reg   [10:0] empty_reg_656;
wire   [0:0] and_ln78_fu_356_p2;
reg   [0:0] and_ln78_reg_661;
wire   [10:0] p_mid1386_fu_417_p2;
reg   [10:0] p_mid1386_reg_666;
wire   [0:0] select_ln80_3_fu_465_p3;
reg   [0:0] select_ln80_3_reg_671;
wire   [0:0] icmp_ln85_fu_489_p2;
reg   [0:0] icmp_ln85_reg_681;
wire   [0:0] icmp_ln85_1_fu_495_p2;
reg   [0:0] icmp_ln85_1_reg_686;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] zext_ln85_fu_517_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln83_fu_559_p1;
reg   [4:0] i_fu_74;
wire   [4:0] add_ln82_fu_522_p2;
wire    ap_loop_init;
reg   [4:0] n_fu_78;
wire   [4:0] select_ln80_4_fu_473_p3;
reg   [9:0] indvar_flatten390_fu_82;
wire   [9:0] select_ln80_5_fu_196_p3;
reg   [9:0] ap_sig_allocacmp_indvar_flatten390_load;
reg   [3:0] c_fu_86;
wire   [3:0] select_ln78_1_fu_178_p3;
reg   [3:0] ap_sig_allocacmp_c_2;
reg   [12:0] indvar_flatten442_fu_90;
wire   [12:0] add_ln78_fu_157_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten442_load;
wire   [9:0] add_ln80_1_fu_190_p2;
wire   [3:0] mul_ln80_fu_225_p0;
wire   [10:0] mul_ln80_fu_225_p1;
wire   [9:0] p_shl_fu_243_p3;
wire   [5:0] p_shl4_fu_255_p3;
wire   [10:0] p_shl27_cast_fu_251_p1;
wire   [10:0] p_shl28_cast_fu_263_p1;
wire   [6:0] p_shl5_fu_273_p3;
wire   [10:0] p_shl26_cast_fu_281_p1;
wire   [10:0] empty_495_fu_285_p2;
wire   [12:0] mul_ln80_fu_225_p2;
wire  signed [12:0] sext_ln82_fu_291_p1;
wire   [0:0] cmp9_i146_fu_231_p2;
wire   [0:0] cmp10_i147_fu_237_p2;
wire   [3:0] mul_ln80_1_fu_320_p0;
wire   [10:0] mul_ln80_1_fu_320_p1;
wire   [12:0] mul_ln80_1_fu_320_p2;
wire   [12:0] add_ln85_fu_295_p2;
wire   [0:0] or_ln85_fu_301_p2;
wire   [0:0] icmp_ln82_fu_350_p2;
wire   [0:0] xor_ln78_fu_345_p2;
wire   [4:0] select_ln78_fu_310_p3;
wire   [0:0] or_ln80_fu_368_p2;
wire   [4:0] add_ln80_fu_362_p2;
wire   [9:0] p_shl27_mid1_fu_393_p3;
wire   [5:0] p_shl28_mid1_fu_405_p3;
wire   [10:0] p_shl27_cast_mid1_fu_401_p1;
wire   [10:0] p_shl28_cast_mid1_fu_413_p1;
wire   [6:0] p_shl26_mid1_fu_423_p3;
wire   [10:0] p_shl26_cast_mid1_fu_431_p1;
wire   [10:0] p_mid1388_fu_435_p2;
wire   [12:0] select_ln78_2_fu_326_p3;
wire  signed [12:0] sext_ln82_1_fu_441_p1;
wire   [12:0] add_ln85_3_fu_445_p2;
wire   [12:0] select_ln78_4_fu_333_p3;
wire   [0:0] cmp9_i146_mid1_fu_381_p2;
wire   [0:0] cmp10_i147_mid1_fu_387_p2;
wire   [0:0] or_ln85_3_fu_459_p2;
wire   [0:0] or_ln78_fu_340_p2;
wire   [4:0] select_ln80_fu_373_p3;
wire   [5:0] i_3_cast94_fu_481_p1;
wire   [5:0] add_ln85_2_fu_501_p2;
wire  signed [12:0] sext_ln85_fu_507_p1;
wire   [12:0] select_ln80_2_fu_451_p3;
wire   [12:0] add_ln85_1_fu_511_p2;
wire   [10:0] select_ln78_3_fu_538_p3;
wire   [10:0] select_ln80_1_fu_544_p3;
wire   [12:0] grp_fu_582_p3;
wire  signed [12:0] select_ln80_1_cast_fu_550_p1;
(* use_dsp48 = "no" *) wire   [12:0] add_ln83_fu_554_p2;
wire   [0:0] or_ln85_1_fu_564_p2;
wire   [0:0] or_ln85_2_fu_568_p2;
wire   [3:0] grp_fu_582_p0;
wire   [9:0] grp_fu_582_p1;
wire   [4:0] grp_fu_582_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [12:0] grp_fu_582_p00;
wire   [12:0] grp_fu_582_p20;
wire   [12:0] mul_ln80_1_fu_320_p00;
wire   [12:0] mul_ln80_fu_225_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
end

inference_top_mul_4ns_11ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 13 ))
mul_4ns_11ns_13_1_1_U79(
    .din0(mul_ln80_fu_225_p0),
    .din1(mul_ln80_fu_225_p1),
    .dout(mul_ln80_fu_225_p2)
);

inference_top_mul_4ns_11ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 13 ))
mul_4ns_11ns_13_1_1_U80(
    .din0(mul_ln80_1_fu_320_p0),
    .din1(mul_ln80_1_fu_320_p1),
    .dout(mul_ln80_1_fu_320_p2)
);

inference_top_mac_muladd_4ns_10ns_5ns_13_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
mac_muladd_4ns_10ns_5ns_13_4_1_U81(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_582_p0),
    .din1(grp_fu_582_p1),
    .din2(grp_fu_582_p2),
    .ce(1'b1),
    .dout(grp_fu_582_p3)
);

inference_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln78_fu_151_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_86 <= select_ln78_1_fu_178_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_86 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            i_fu_74 <= 5'd0;
        end else if (((icmp_ln78_reg_631_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            i_fu_74 <= add_ln82_fu_522_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln78_fu_151_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten390_fu_82 <= select_ln80_5_fu_196_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten390_fu_82 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln78_fu_151_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten442_fu_90 <= add_ln78_fu_157_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten442_fu_90 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            n_fu_78 <= 5'd0;
        end else if (((icmp_ln78_reg_631_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            n_fu_78 <= select_ln80_4_fu_473_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln78_fu_151_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln78_1_reg_646 <= add_ln78_1_fu_172_p2;
        icmp_ln80_reg_635 <= icmp_ln80_fu_166_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln78_1_reg_646_pp0_iter1_reg <= add_ln78_1_reg_646;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        c_2_reg_626 <= ap_sig_allocacmp_c_2;
        c_2_reg_626_pp0_iter1_reg <= c_2_reg_626;
        icmp_ln78_reg_631 <= icmp_ln78_fu_151_p2;
        icmp_ln78_reg_631_pp0_iter1_reg <= icmp_ln78_reg_631;
        icmp_ln80_reg_635_pp0_iter1_reg <= icmp_ln80_reg_635;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln78_reg_631_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln78_reg_661 <= and_ln78_fu_356_p2;
        icmp_ln85_1_reg_686 <= icmp_ln85_1_fu_495_p2;
        icmp_ln85_reg_681 <= icmp_ln85_fu_489_p2;
        p_mid1386_reg_666[10 : 1] <= p_mid1386_fu_417_p2[10 : 1];
        select_ln80_3_reg_671 <= select_ln80_3_fu_465_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln80_reg_635_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_reg_656[10 : 1] <= empty_fu_267_p2[10 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln80_reg_635_pp0_iter2_reg <= icmp_ln80_reg_635_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        OutPadConv2_V_ce0 = 1'b1;
    end else begin
        OutPadConv2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        OutPadConv2_V_we0 = 1'b1;
    end else begin
        OutPadConv2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln78_fu_151_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln78_reg_631_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_2 = 4'd0;
    end else begin
        ap_sig_allocacmp_c_2 = c_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten390_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten390_load = indvar_flatten390_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten442_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten442_load = indvar_flatten442_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        upsample_V_ce0 = 1'b1;
    end else begin
        upsample_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OutPadConv2_V_address0 = zext_ln83_fu_559_p1;

assign OutPadConv2_V_d0 = ((or_ln85_2_fu_568_p2[0:0] == 1'b1) ? 16'd0 : upsample_V_q0);

assign add_ln78_1_fu_172_p2 = (ap_sig_allocacmp_c_2 + 4'd1);

assign add_ln78_fu_157_p2 = (ap_sig_allocacmp_indvar_flatten442_load + 13'd1);

assign add_ln80_1_fu_190_p2 = (ap_sig_allocacmp_indvar_flatten390_load + 10'd1);

assign add_ln80_fu_362_p2 = (select_ln78_fu_310_p3 + 5'd1);

assign add_ln82_fu_522_p2 = (select_ln80_fu_373_p3 + 5'd1);

assign add_ln83_fu_554_p2 = ($signed(grp_fu_582_p3) + $signed(select_ln80_1_cast_fu_550_p1));

assign add_ln85_1_fu_511_p2 = ($signed(sext_ln85_fu_507_p1) + $signed(select_ln80_2_fu_451_p3));

assign add_ln85_2_fu_501_p2 = ($signed(i_3_cast94_fu_481_p1) + $signed(6'd35));

assign add_ln85_3_fu_445_p2 = ($signed(select_ln78_2_fu_326_p3) + $signed(sext_ln82_1_fu_441_p1));

assign add_ln85_fu_295_p2 = ($signed(mul_ln80_fu_225_p2) + $signed(sext_ln82_fu_291_p1));

assign and_ln78_fu_356_p2 = (xor_ln78_fu_345_p2 & icmp_ln82_fu_350_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cmp10_i147_fu_237_p2 = ((n_fu_78 > 5'd28) ? 1'b1 : 1'b0);

assign cmp10_i147_mid1_fu_387_p2 = ((add_ln80_fu_362_p2 > 5'd28) ? 1'b1 : 1'b0);

assign cmp9_i146_fu_231_p2 = ((n_fu_78 == 5'd0) ? 1'b1 : 1'b0);

assign cmp9_i146_mid1_fu_381_p2 = ((add_ln80_fu_362_p2 == 5'd0) ? 1'b1 : 1'b0);

assign empty_495_fu_285_p2 = (p_shl27_cast_fu_251_p1 - p_shl26_cast_fu_281_p1);

assign empty_fu_267_p2 = (p_shl27_cast_fu_251_p1 - p_shl28_cast_fu_263_p1);

assign grp_fu_582_p0 = grp_fu_582_p00;

assign grp_fu_582_p00 = select_ln78_1_fu_178_p3;

assign grp_fu_582_p1 = 13'd900;

assign grp_fu_582_p2 = grp_fu_582_p20;

assign grp_fu_582_p20 = select_ln80_fu_373_p3;

assign i_3_cast94_fu_481_p1 = select_ln80_fu_373_p3;

assign icmp_ln78_fu_151_p2 = ((ap_sig_allocacmp_indvar_flatten442_load == 13'd7200) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_166_p2 = ((ap_sig_allocacmp_indvar_flatten390_load == 10'd900) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_350_p2 = ((i_fu_74 == 5'd30) ? 1'b1 : 1'b0);

assign icmp_ln85_1_fu_495_p2 = ((select_ln80_fu_373_p3 > 5'd28) ? 1'b1 : 1'b0);

assign icmp_ln85_fu_489_p2 = ((select_ln80_fu_373_p3 == 5'd0) ? 1'b1 : 1'b0);

assign mul_ln80_1_fu_320_p0 = mul_ln80_1_fu_320_p00;

assign mul_ln80_1_fu_320_p00 = add_ln78_1_reg_646_pp0_iter1_reg;

assign mul_ln80_1_fu_320_p1 = 13'd784;

assign mul_ln80_fu_225_p0 = mul_ln80_fu_225_p00;

assign mul_ln80_fu_225_p00 = c_2_reg_626_pp0_iter1_reg;

assign mul_ln80_fu_225_p1 = 13'd784;

assign or_ln78_fu_340_p2 = (or_ln85_fu_301_p2 | icmp_ln80_reg_635_pp0_iter1_reg);

assign or_ln80_fu_368_p2 = (icmp_ln80_reg_635_pp0_iter1_reg | and_ln78_fu_356_p2);

assign or_ln85_1_fu_564_p2 = (icmp_ln85_reg_681 | icmp_ln85_1_reg_686);

assign or_ln85_2_fu_568_p2 = (select_ln80_3_reg_671 | or_ln85_1_fu_564_p2);

assign or_ln85_3_fu_459_p2 = (cmp9_i146_mid1_fu_381_p2 | cmp10_i147_mid1_fu_387_p2);

assign or_ln85_fu_301_p2 = (cmp9_i146_fu_231_p2 | cmp10_i147_fu_237_p2);

assign p_mid1386_fu_417_p2 = (p_shl27_cast_mid1_fu_401_p1 - p_shl28_cast_mid1_fu_413_p1);

assign p_mid1388_fu_435_p2 = (p_shl27_cast_mid1_fu_401_p1 - p_shl26_cast_mid1_fu_431_p1);

assign p_shl26_cast_fu_281_p1 = p_shl5_fu_273_p3;

assign p_shl26_cast_mid1_fu_431_p1 = p_shl26_mid1_fu_423_p3;

assign p_shl26_mid1_fu_423_p3 = {{add_ln80_fu_362_p2}, {2'd0}};

assign p_shl27_cast_fu_251_p1 = p_shl_fu_243_p3;

assign p_shl27_cast_mid1_fu_401_p1 = p_shl27_mid1_fu_393_p3;

assign p_shl27_mid1_fu_393_p3 = {{add_ln80_fu_362_p2}, {5'd0}};

assign p_shl28_cast_fu_263_p1 = p_shl4_fu_255_p3;

assign p_shl28_cast_mid1_fu_413_p1 = p_shl28_mid1_fu_405_p3;

assign p_shl28_mid1_fu_405_p3 = {{add_ln80_fu_362_p2}, {1'd0}};

assign p_shl4_fu_255_p3 = {{n_fu_78}, {1'd0}};

assign p_shl5_fu_273_p3 = {{n_fu_78}, {2'd0}};

assign p_shl_fu_243_p3 = {{n_fu_78}, {5'd0}};

assign select_ln78_1_fu_178_p3 = ((icmp_ln80_fu_166_p2[0:0] == 1'b1) ? add_ln78_1_fu_172_p2 : ap_sig_allocacmp_c_2);

assign select_ln78_2_fu_326_p3 = ((icmp_ln80_reg_635_pp0_iter1_reg[0:0] == 1'b1) ? mul_ln80_1_fu_320_p2 : mul_ln80_fu_225_p2);

assign select_ln78_3_fu_538_p3 = ((icmp_ln80_reg_635_pp0_iter2_reg[0:0] == 1'b1) ? 11'd0 : empty_reg_656);

assign select_ln78_4_fu_333_p3 = ((icmp_ln80_reg_635_pp0_iter1_reg[0:0] == 1'b1) ? mul_ln80_1_fu_320_p2 : add_ln85_fu_295_p2);

assign select_ln78_fu_310_p3 = ((icmp_ln80_reg_635_pp0_iter1_reg[0:0] == 1'b1) ? 5'd0 : n_fu_78);

assign select_ln80_1_cast_fu_550_p1 = $signed(select_ln80_1_fu_544_p3);

assign select_ln80_1_fu_544_p3 = ((and_ln78_reg_661[0:0] == 1'b1) ? p_mid1386_reg_666 : select_ln78_3_fu_538_p3);

assign select_ln80_2_fu_451_p3 = ((and_ln78_fu_356_p2[0:0] == 1'b1) ? add_ln85_3_fu_445_p2 : select_ln78_4_fu_333_p3);

assign select_ln80_3_fu_465_p3 = ((and_ln78_fu_356_p2[0:0] == 1'b1) ? or_ln85_3_fu_459_p2 : or_ln78_fu_340_p2);

assign select_ln80_4_fu_473_p3 = ((and_ln78_fu_356_p2[0:0] == 1'b1) ? add_ln80_fu_362_p2 : select_ln78_fu_310_p3);

assign select_ln80_5_fu_196_p3 = ((icmp_ln80_fu_166_p2[0:0] == 1'b1) ? 10'd1 : add_ln80_1_fu_190_p2);

assign select_ln80_fu_373_p3 = ((or_ln80_fu_368_p2[0:0] == 1'b1) ? 5'd0 : i_fu_74);

assign sext_ln82_1_fu_441_p1 = $signed(p_mid1388_fu_435_p2);

assign sext_ln82_fu_291_p1 = $signed(empty_495_fu_285_p2);

assign sext_ln85_fu_507_p1 = $signed(add_ln85_2_fu_501_p2);

assign upsample_V_address0 = zext_ln85_fu_517_p1;

assign xor_ln78_fu_345_p2 = (icmp_ln80_reg_635_pp0_iter1_reg ^ 1'd1);

assign zext_ln83_fu_559_p1 = add_ln83_fu_554_p2;

assign zext_ln85_fu_517_p1 = add_ln85_1_fu_511_p2;

always @ (posedge ap_clk) begin
    empty_reg_656[0] <= 1'b0;
    p_mid1386_reg_666[0] <= 1'b0;
end

endmodule //inference_top_D_CNN_Pipeline_loop_for_3_channel_pad_2_loop_for_channel_pad_2_loop_for_weight_p
