// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="inference_top_inference_top,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=660921,HLS_SYN_TPT=none,HLS_SYN_MEM=61,HLS_SYN_DSP=0,HLS_SYN_FF=18976,HLS_SYN_LUT=34399,HLS_VERSION=2022_2}" *)

module inference_top (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt,
        s_axi_control_r_AWVALID,
        s_axi_control_r_AWREADY,
        s_axi_control_r_AWADDR,
        s_axi_control_r_WVALID,
        s_axi_control_r_WREADY,
        s_axi_control_r_WDATA,
        s_axi_control_r_WSTRB,
        s_axi_control_r_ARVALID,
        s_axi_control_r_ARREADY,
        s_axi_control_r_ARADDR,
        s_axi_control_r_RVALID,
        s_axi_control_r_RREADY,
        s_axi_control_r_RDATA,
        s_axi_control_r_RRESP,
        s_axi_control_r_BVALID,
        s_axi_control_r_BREADY,
        s_axi_control_r_BRESP
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_R_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_R_ADDR_WIDTH = 6;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_CONTROL_R_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;
input   s_axi_control_r_AWVALID;
output   s_axi_control_r_AWREADY;
input  [C_S_AXI_CONTROL_R_ADDR_WIDTH - 1:0] s_axi_control_r_AWADDR;
input   s_axi_control_r_WVALID;
output   s_axi_control_r_WREADY;
input  [C_S_AXI_CONTROL_R_DATA_WIDTH - 1:0] s_axi_control_r_WDATA;
input  [C_S_AXI_CONTROL_R_WSTRB_WIDTH - 1:0] s_axi_control_r_WSTRB;
input   s_axi_control_r_ARVALID;
output   s_axi_control_r_ARREADY;
input  [C_S_AXI_CONTROL_R_ADDR_WIDTH - 1:0] s_axi_control_r_ARADDR;
output   s_axi_control_r_RVALID;
input   s_axi_control_r_RREADY;
output  [C_S_AXI_CONTROL_R_DATA_WIDTH - 1:0] s_axi_control_r_RDATA;
output  [1:0] s_axi_control_r_RRESP;
output   s_axi_control_r_BVALID;
input   s_axi_control_r_BREADY;
output  [1:0] s_axi_control_r_BRESP;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] input_r;
wire   [31:0] digit;
reg    digit_ap_vld;
wire   [63:0] denoiser_w;
wire   [63:0] classifier_w;
reg   [63:0] classifier_w_read_reg_192;
reg   [63:0] denoiser_w_read_reg_197;
reg   [63:0] input_r_read_reg_202;
reg   [9:0] denoised_V_address0;
reg    denoised_V_ce0;
reg    denoised_V_we0;
wire   [15:0] denoised_V_q0;
reg    denoised_V_ce1;
wire   [15:0] denoised_V_q1;
wire    grp_D_CNN_fu_109_ap_start;
wire    grp_D_CNN_fu_109_ap_done;
wire    grp_D_CNN_fu_109_ap_idle;
wire    grp_D_CNN_fu_109_ap_ready;
wire    grp_D_CNN_fu_109_m_axi_gmem0_AWVALID;
wire   [63:0] grp_D_CNN_fu_109_m_axi_gmem0_AWADDR;
wire   [0:0] grp_D_CNN_fu_109_m_axi_gmem0_AWID;
wire   [31:0] grp_D_CNN_fu_109_m_axi_gmem0_AWLEN;
wire   [2:0] grp_D_CNN_fu_109_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_D_CNN_fu_109_m_axi_gmem0_AWBURST;
wire   [1:0] grp_D_CNN_fu_109_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_D_CNN_fu_109_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_D_CNN_fu_109_m_axi_gmem0_AWPROT;
wire   [3:0] grp_D_CNN_fu_109_m_axi_gmem0_AWQOS;
wire   [3:0] grp_D_CNN_fu_109_m_axi_gmem0_AWREGION;
wire   [0:0] grp_D_CNN_fu_109_m_axi_gmem0_AWUSER;
wire    grp_D_CNN_fu_109_m_axi_gmem0_WVALID;
wire   [15:0] grp_D_CNN_fu_109_m_axi_gmem0_WDATA;
wire   [1:0] grp_D_CNN_fu_109_m_axi_gmem0_WSTRB;
wire    grp_D_CNN_fu_109_m_axi_gmem0_WLAST;
wire   [0:0] grp_D_CNN_fu_109_m_axi_gmem0_WID;
wire   [0:0] grp_D_CNN_fu_109_m_axi_gmem0_WUSER;
wire    grp_D_CNN_fu_109_m_axi_gmem0_ARVALID;
wire   [63:0] grp_D_CNN_fu_109_m_axi_gmem0_ARADDR;
wire   [0:0] grp_D_CNN_fu_109_m_axi_gmem0_ARID;
wire   [31:0] grp_D_CNN_fu_109_m_axi_gmem0_ARLEN;
wire   [2:0] grp_D_CNN_fu_109_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_D_CNN_fu_109_m_axi_gmem0_ARBURST;
wire   [1:0] grp_D_CNN_fu_109_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_D_CNN_fu_109_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_D_CNN_fu_109_m_axi_gmem0_ARPROT;
wire   [3:0] grp_D_CNN_fu_109_m_axi_gmem0_ARQOS;
wire   [3:0] grp_D_CNN_fu_109_m_axi_gmem0_ARREGION;
wire   [0:0] grp_D_CNN_fu_109_m_axi_gmem0_ARUSER;
wire    grp_D_CNN_fu_109_m_axi_gmem0_RREADY;
wire    grp_D_CNN_fu_109_m_axi_gmem0_BREADY;
wire   [9:0] grp_D_CNN_fu_109_OutModel0_address0;
wire    grp_D_CNN_fu_109_OutModel0_ce0;
wire    grp_D_CNN_fu_109_OutModel0_we0;
wire   [15:0] grp_D_CNN_fu_109_OutModel0_d0;
wire    grp_D_CNN_fu_109_m_axi_gmem1_AWVALID;
wire   [63:0] grp_D_CNN_fu_109_m_axi_gmem1_AWADDR;
wire   [0:0] grp_D_CNN_fu_109_m_axi_gmem1_AWID;
wire   [31:0] grp_D_CNN_fu_109_m_axi_gmem1_AWLEN;
wire   [2:0] grp_D_CNN_fu_109_m_axi_gmem1_AWSIZE;
wire   [1:0] grp_D_CNN_fu_109_m_axi_gmem1_AWBURST;
wire   [1:0] grp_D_CNN_fu_109_m_axi_gmem1_AWLOCK;
wire   [3:0] grp_D_CNN_fu_109_m_axi_gmem1_AWCACHE;
wire   [2:0] grp_D_CNN_fu_109_m_axi_gmem1_AWPROT;
wire   [3:0] grp_D_CNN_fu_109_m_axi_gmem1_AWQOS;
wire   [3:0] grp_D_CNN_fu_109_m_axi_gmem1_AWREGION;
wire   [0:0] grp_D_CNN_fu_109_m_axi_gmem1_AWUSER;
wire    grp_D_CNN_fu_109_m_axi_gmem1_WVALID;
wire   [15:0] grp_D_CNN_fu_109_m_axi_gmem1_WDATA;
wire   [1:0] grp_D_CNN_fu_109_m_axi_gmem1_WSTRB;
wire    grp_D_CNN_fu_109_m_axi_gmem1_WLAST;
wire   [0:0] grp_D_CNN_fu_109_m_axi_gmem1_WID;
wire   [0:0] grp_D_CNN_fu_109_m_axi_gmem1_WUSER;
wire    grp_D_CNN_fu_109_m_axi_gmem1_ARVALID;
wire   [63:0] grp_D_CNN_fu_109_m_axi_gmem1_ARADDR;
wire   [0:0] grp_D_CNN_fu_109_m_axi_gmem1_ARID;
wire   [31:0] grp_D_CNN_fu_109_m_axi_gmem1_ARLEN;
wire   [2:0] grp_D_CNN_fu_109_m_axi_gmem1_ARSIZE;
wire   [1:0] grp_D_CNN_fu_109_m_axi_gmem1_ARBURST;
wire   [1:0] grp_D_CNN_fu_109_m_axi_gmem1_ARLOCK;
wire   [3:0] grp_D_CNN_fu_109_m_axi_gmem1_ARCACHE;
wire   [2:0] grp_D_CNN_fu_109_m_axi_gmem1_ARPROT;
wire   [3:0] grp_D_CNN_fu_109_m_axi_gmem1_ARQOS;
wire   [3:0] grp_D_CNN_fu_109_m_axi_gmem1_ARREGION;
wire   [0:0] grp_D_CNN_fu_109_m_axi_gmem1_ARUSER;
wire    grp_D_CNN_fu_109_m_axi_gmem1_RREADY;
wire    grp_D_CNN_fu_109_m_axi_gmem1_BREADY;
wire    grp_C_CNN_fu_123_ap_start;
wire    grp_C_CNN_fu_123_ap_done;
wire    grp_C_CNN_fu_123_ap_idle;
wire    grp_C_CNN_fu_123_ap_ready;
wire   [9:0] grp_C_CNN_fu_123_InModel_address0;
wire    grp_C_CNN_fu_123_InModel_ce0;
wire   [9:0] grp_C_CNN_fu_123_InModel_address1;
wire    grp_C_CNN_fu_123_InModel_ce1;
wire    grp_C_CNN_fu_123_m_axi_gmem1_AWVALID;
wire   [63:0] grp_C_CNN_fu_123_m_axi_gmem1_AWADDR;
wire   [0:0] grp_C_CNN_fu_123_m_axi_gmem1_AWID;
wire   [31:0] grp_C_CNN_fu_123_m_axi_gmem1_AWLEN;
wire   [2:0] grp_C_CNN_fu_123_m_axi_gmem1_AWSIZE;
wire   [1:0] grp_C_CNN_fu_123_m_axi_gmem1_AWBURST;
wire   [1:0] grp_C_CNN_fu_123_m_axi_gmem1_AWLOCK;
wire   [3:0] grp_C_CNN_fu_123_m_axi_gmem1_AWCACHE;
wire   [2:0] grp_C_CNN_fu_123_m_axi_gmem1_AWPROT;
wire   [3:0] grp_C_CNN_fu_123_m_axi_gmem1_AWQOS;
wire   [3:0] grp_C_CNN_fu_123_m_axi_gmem1_AWREGION;
wire   [0:0] grp_C_CNN_fu_123_m_axi_gmem1_AWUSER;
wire    grp_C_CNN_fu_123_m_axi_gmem1_WVALID;
wire   [15:0] grp_C_CNN_fu_123_m_axi_gmem1_WDATA;
wire   [1:0] grp_C_CNN_fu_123_m_axi_gmem1_WSTRB;
wire    grp_C_CNN_fu_123_m_axi_gmem1_WLAST;
wire   [0:0] grp_C_CNN_fu_123_m_axi_gmem1_WID;
wire   [0:0] grp_C_CNN_fu_123_m_axi_gmem1_WUSER;
wire    grp_C_CNN_fu_123_m_axi_gmem1_ARVALID;
wire   [63:0] grp_C_CNN_fu_123_m_axi_gmem1_ARADDR;
wire   [0:0] grp_C_CNN_fu_123_m_axi_gmem1_ARID;
wire   [31:0] grp_C_CNN_fu_123_m_axi_gmem1_ARLEN;
wire   [2:0] grp_C_CNN_fu_123_m_axi_gmem1_ARSIZE;
wire   [1:0] grp_C_CNN_fu_123_m_axi_gmem1_ARBURST;
wire   [1:0] grp_C_CNN_fu_123_m_axi_gmem1_ARLOCK;
wire   [3:0] grp_C_CNN_fu_123_m_axi_gmem1_ARCACHE;
wire   [2:0] grp_C_CNN_fu_123_m_axi_gmem1_ARPROT;
wire   [3:0] grp_C_CNN_fu_123_m_axi_gmem1_ARQOS;
wire   [3:0] grp_C_CNN_fu_123_m_axi_gmem1_ARREGION;
wire   [0:0] grp_C_CNN_fu_123_m_axi_gmem1_ARUSER;
wire    grp_C_CNN_fu_123_m_axi_gmem1_RREADY;
wire    grp_C_CNN_fu_123_m_axi_gmem1_BREADY;
wire   [15:0] grp_C_CNN_fu_123_ap_return;
wire    gmem0_AWREADY;
wire    gmem0_WREADY;
reg    gmem0_ARVALID;
wire    gmem0_ARREADY;
wire    gmem0_RVALID;
reg    gmem0_RREADY;
wire   [15:0] gmem0_RDATA;
wire   [9:0] gmem0_RFIFONUM;
wire    gmem0_BVALID;
wire    gmem1_AWREADY;
wire    gmem1_WREADY;
reg    gmem1_ARVALID;
wire    gmem1_ARREADY;
reg   [63:0] gmem1_ARADDR;
reg   [31:0] gmem1_ARLEN;
wire    gmem1_RVALID;
reg    gmem1_RREADY;
wire   [15:0] gmem1_RDATA;
wire   [9:0] gmem1_RFIFONUM;
wire    gmem1_BVALID;
reg    grp_D_CNN_fu_109_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_C_CNN_fu_123_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire   [7:0] trunc_ln1003_fu_155_p1;
wire   [7:0] ret_V_fu_137_p4;
wire   [0:0] icmp_ln1003_fu_159_p2;
wire   [7:0] ret_V_1_fu_165_p2;
wire   [0:0] p_Result_s_fu_147_p3;
wire   [7:0] select_ln1002_fu_171_p3;
wire   [7:0] ret_V_2_fu_179_p3;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_D_CNN_fu_109_ap_start_reg = 1'b0;
#0 grp_C_CNN_fu_123_ap_start_reg = 1'b0;
end

inference_top_denoised_V_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
denoised_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(denoised_V_address0),
    .ce0(denoised_V_ce0),
    .we0(denoised_V_we0),
    .d0(grp_D_CNN_fu_109_OutModel0_d0),
    .q0(denoised_V_q0),
    .address1(grp_C_CNN_fu_123_InModel_address1),
    .ce1(denoised_V_ce1),
    .q1(denoised_V_q1)
);

inference_top_D_CNN grp_D_CNN_fu_109(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_D_CNN_fu_109_ap_start),
    .ap_done(grp_D_CNN_fu_109_ap_done),
    .ap_idle(grp_D_CNN_fu_109_ap_idle),
    .ap_ready(grp_D_CNN_fu_109_ap_ready),
    .m_axi_gmem0_AWVALID(grp_D_CNN_fu_109_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_D_CNN_fu_109_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_D_CNN_fu_109_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_D_CNN_fu_109_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_D_CNN_fu_109_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_D_CNN_fu_109_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_D_CNN_fu_109_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_D_CNN_fu_109_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_D_CNN_fu_109_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_D_CNN_fu_109_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_D_CNN_fu_109_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_D_CNN_fu_109_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_D_CNN_fu_109_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_D_CNN_fu_109_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_D_CNN_fu_109_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_D_CNN_fu_109_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_D_CNN_fu_109_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_D_CNN_fu_109_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_D_CNN_fu_109_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_D_CNN_fu_109_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_D_CNN_fu_109_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_D_CNN_fu_109_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_D_CNN_fu_109_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_D_CNN_fu_109_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_D_CNN_fu_109_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_D_CNN_fu_109_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_D_CNN_fu_109_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_D_CNN_fu_109_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_D_CNN_fu_109_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_D_CNN_fu_109_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_D_CNN_fu_109_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem0_RDATA),
    .m_axi_gmem0_RLAST(1'b0),
    .m_axi_gmem0_RID(1'd0),
    .m_axi_gmem0_RFIFONUM(gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(1'd0),
    .m_axi_gmem0_RRESP(2'd0),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_D_CNN_fu_109_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .InModel(input_r_read_reg_202),
    .OutModel0_address0(grp_D_CNN_fu_109_OutModel0_address0),
    .OutModel0_ce0(grp_D_CNN_fu_109_OutModel0_ce0),
    .OutModel0_we0(grp_D_CNN_fu_109_OutModel0_we0),
    .OutModel0_d0(grp_D_CNN_fu_109_OutModel0_d0),
    .m_axi_gmem1_AWVALID(grp_D_CNN_fu_109_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(grp_D_CNN_fu_109_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(grp_D_CNN_fu_109_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(grp_D_CNN_fu_109_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(grp_D_CNN_fu_109_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(grp_D_CNN_fu_109_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(grp_D_CNN_fu_109_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(grp_D_CNN_fu_109_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(grp_D_CNN_fu_109_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(grp_D_CNN_fu_109_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(grp_D_CNN_fu_109_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(grp_D_CNN_fu_109_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(grp_D_CNN_fu_109_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(grp_D_CNN_fu_109_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(grp_D_CNN_fu_109_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(grp_D_CNN_fu_109_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(grp_D_CNN_fu_109_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(grp_D_CNN_fu_109_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(grp_D_CNN_fu_109_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(grp_D_CNN_fu_109_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(grp_D_CNN_fu_109_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(grp_D_CNN_fu_109_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(grp_D_CNN_fu_109_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(grp_D_CNN_fu_109_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(grp_D_CNN_fu_109_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(grp_D_CNN_fu_109_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(grp_D_CNN_fu_109_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(grp_D_CNN_fu_109_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(grp_D_CNN_fu_109_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(grp_D_CNN_fu_109_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(gmem1_RVALID),
    .m_axi_gmem1_RREADY(grp_D_CNN_fu_109_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(gmem1_RDATA),
    .m_axi_gmem1_RLAST(1'b0),
    .m_axi_gmem1_RID(1'd0),
    .m_axi_gmem1_RFIFONUM(gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(1'd0),
    .m_axi_gmem1_RRESP(2'd0),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(grp_D_CNN_fu_109_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .Weights(denoiser_w_read_reg_197)
);

inference_top_C_CNN grp_C_CNN_fu_123(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_C_CNN_fu_123_ap_start),
    .ap_done(grp_C_CNN_fu_123_ap_done),
    .ap_idle(grp_C_CNN_fu_123_ap_idle),
    .ap_ready(grp_C_CNN_fu_123_ap_ready),
    .InModel_address0(grp_C_CNN_fu_123_InModel_address0),
    .InModel_ce0(grp_C_CNN_fu_123_InModel_ce0),
    .InModel_q0(denoised_V_q0),
    .InModel_address1(grp_C_CNN_fu_123_InModel_address1),
    .InModel_ce1(grp_C_CNN_fu_123_InModel_ce1),
    .InModel_q1(denoised_V_q1),
    .m_axi_gmem1_AWVALID(grp_C_CNN_fu_123_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(grp_C_CNN_fu_123_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(grp_C_CNN_fu_123_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(grp_C_CNN_fu_123_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(grp_C_CNN_fu_123_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(grp_C_CNN_fu_123_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(grp_C_CNN_fu_123_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(grp_C_CNN_fu_123_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(grp_C_CNN_fu_123_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(grp_C_CNN_fu_123_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(grp_C_CNN_fu_123_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(grp_C_CNN_fu_123_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(grp_C_CNN_fu_123_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(grp_C_CNN_fu_123_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(grp_C_CNN_fu_123_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(grp_C_CNN_fu_123_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(grp_C_CNN_fu_123_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(grp_C_CNN_fu_123_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(grp_C_CNN_fu_123_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(grp_C_CNN_fu_123_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(grp_C_CNN_fu_123_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(grp_C_CNN_fu_123_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(grp_C_CNN_fu_123_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(grp_C_CNN_fu_123_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(grp_C_CNN_fu_123_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(grp_C_CNN_fu_123_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(grp_C_CNN_fu_123_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(grp_C_CNN_fu_123_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(grp_C_CNN_fu_123_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(grp_C_CNN_fu_123_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(gmem1_RVALID),
    .m_axi_gmem1_RREADY(grp_C_CNN_fu_123_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(gmem1_RDATA),
    .m_axi_gmem1_RLAST(1'b0),
    .m_axi_gmem1_RID(1'd0),
    .m_axi_gmem1_RFIFONUM(gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(1'd0),
    .m_axi_gmem1_RRESP(2'd0),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(grp_C_CNN_fu_123_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .Weights(classifier_w_read_reg_192),
    .ap_return(grp_C_CNN_fu_123_ap_return)
);

inference_top_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .digit(digit),
    .digit_ap_vld(digit_ap_vld),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

inference_top_control_r_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_R_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_R_DATA_WIDTH ))
control_r_s_axi_U(
    .AWVALID(s_axi_control_r_AWVALID),
    .AWREADY(s_axi_control_r_AWREADY),
    .AWADDR(s_axi_control_r_AWADDR),
    .WVALID(s_axi_control_r_WVALID),
    .WREADY(s_axi_control_r_WREADY),
    .WDATA(s_axi_control_r_WDATA),
    .WSTRB(s_axi_control_r_WSTRB),
    .ARVALID(s_axi_control_r_ARVALID),
    .ARREADY(s_axi_control_r_ARREADY),
    .ARADDR(s_axi_control_r_ARADDR),
    .RVALID(s_axi_control_r_RVALID),
    .RREADY(s_axi_control_r_RREADY),
    .RDATA(s_axi_control_r_RDATA),
    .RRESP(s_axi_control_r_RRESP),
    .BVALID(s_axi_control_r_BVALID),
    .BREADY(s_axi_control_r_BREADY),
    .BRESP(s_axi_control_r_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_r(input_r),
    .denoiser_w(denoiser_w),
    .classifier_w(classifier_w)
);

inference_top_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 10 ),
    .USER_DW( 16 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem0_ARVALID),
    .I_ARREADY(gmem0_ARREADY),
    .I_ARADDR(grp_D_CNN_fu_109_m_axi_gmem0_ARADDR),
    .I_ARLEN(grp_D_CNN_fu_109_m_axi_gmem0_ARLEN),
    .I_RVALID(gmem0_RVALID),
    .I_RREADY(gmem0_RREADY),
    .I_RDATA(gmem0_RDATA),
    .I_RFIFONUM(gmem0_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem0_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem0_WREADY),
    .I_WDATA(16'd0),
    .I_WSTRB(2'd0),
    .I_BVALID(gmem0_BVALID),
    .I_BREADY(1'b0)
);

inference_top_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 10 ),
    .USER_DW( 16 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem1_ARVALID),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(gmem1_ARADDR),
    .I_ARLEN(gmem1_ARLEN),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(gmem1_RREADY),
    .I_RDATA(gmem1_RDATA),
    .I_RFIFONUM(gmem1_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(16'd0),
    .I_WSTRB(2'd0),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(1'b0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_C_CNN_fu_123_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_C_CNN_fu_123_ap_start_reg <= 1'b1;
        end else if ((grp_C_CNN_fu_123_ap_ready == 1'b1)) begin
            grp_C_CNN_fu_123_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_D_CNN_fu_109_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_D_CNN_fu_109_ap_start_reg <= 1'b1;
        end else if ((grp_D_CNN_fu_109_ap_ready == 1'b1)) begin
            grp_D_CNN_fu_109_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        classifier_w_read_reg_192 <= classifier_w;
        denoiser_w_read_reg_197 <= denoiser_w;
        input_r_read_reg_202 <= input_r;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_D_CNN_fu_109_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_C_CNN_fu_123_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_C_CNN_fu_123_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_C_CNN_fu_123_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        denoised_V_address0 = grp_C_CNN_fu_123_InModel_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        denoised_V_address0 = grp_D_CNN_fu_109_OutModel0_address0;
    end else begin
        denoised_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        denoised_V_ce0 = grp_C_CNN_fu_123_InModel_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        denoised_V_ce0 = grp_D_CNN_fu_109_OutModel0_ce0;
    end else begin
        denoised_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        denoised_V_ce1 = grp_C_CNN_fu_123_InModel_ce1;
    end else begin
        denoised_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        denoised_V_we0 = grp_D_CNN_fu_109_OutModel0_we0;
    end else begin
        denoised_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_C_CNN_fu_123_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        digit_ap_vld = 1'b1;
    end else begin
        digit_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem0_ARVALID = grp_D_CNN_fu_109_m_axi_gmem0_ARVALID;
    end else begin
        gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem0_RREADY = grp_D_CNN_fu_109_m_axi_gmem0_RREADY;
    end else begin
        gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem1_ARADDR = grp_C_CNN_fu_123_m_axi_gmem1_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem1_ARADDR = grp_D_CNN_fu_109_m_axi_gmem1_ARADDR;
    end else begin
        gmem1_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem1_ARLEN = grp_C_CNN_fu_123_m_axi_gmem1_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem1_ARLEN = grp_D_CNN_fu_109_m_axi_gmem1_ARLEN;
    end else begin
        gmem1_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem1_ARVALID = grp_C_CNN_fu_123_m_axi_gmem1_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem1_ARVALID = grp_D_CNN_fu_109_m_axi_gmem1_ARVALID;
    end else begin
        gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem1_RREADY = grp_C_CNN_fu_123_m_axi_gmem1_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem1_RREADY = grp_D_CNN_fu_109_m_axi_gmem1_RREADY;
    end else begin
        gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_D_CNN_fu_109_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_C_CNN_fu_123_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign digit = $signed(ret_V_2_fu_179_p3);

assign grp_C_CNN_fu_123_ap_start = grp_C_CNN_fu_123_ap_start_reg;

assign grp_D_CNN_fu_109_ap_start = grp_D_CNN_fu_109_ap_start_reg;

assign icmp_ln1003_fu_159_p2 = ((trunc_ln1003_fu_155_p1 == 8'd0) ? 1'b1 : 1'b0);

assign p_Result_s_fu_147_p3 = grp_C_CNN_fu_123_ap_return[32'd15];

assign ret_V_1_fu_165_p2 = (ret_V_fu_137_p4 + 8'd1);

assign ret_V_2_fu_179_p3 = ((p_Result_s_fu_147_p3[0:0] == 1'b1) ? select_ln1002_fu_171_p3 : ret_V_fu_137_p4);

assign ret_V_fu_137_p4 = {{grp_C_CNN_fu_123_ap_return[15:8]}};

assign select_ln1002_fu_171_p3 = ((icmp_ln1003_fu_159_p2[0:0] == 1'b1) ? ret_V_fu_137_p4 : ret_V_1_fu_165_p2);

assign trunc_ln1003_fu_155_p1 = grp_C_CNN_fu_123_ap_return[7:0];

endmodule //inference_top
