-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference_top_D_CNN_Pipeline_loop_for_3_channel_pad_1_loop_for_channel_pad_1_loop_for_weight_p is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    OutPadConv1_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    OutPadConv1_V_ce0 : OUT STD_LOGIC;
    OutPadConv1_V_we0 : OUT STD_LOGIC;
    OutPadConv1_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    pool_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pool_V_ce0 : OUT STD_LOGIC;
    pool_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of inference_top_D_CNN_Pipeline_loop_for_3_channel_pad_1_loop_for_channel_pad_1_loop_for_weight_p is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv10_C4 : STD_LOGIC_VECTOR (9 downto 0) := "0011000100";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv10_100 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln41_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal select_ln43_7_fu_422_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln43_7_reg_596 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln46_fu_452_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln46_reg_601 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln48_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_reg_606 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_1_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_1_reg_611 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln48_fu_486_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln46_fu_536_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_1_fu_68 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln45_fu_491_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal n_3_fu_72 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln43_8_fu_430_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten158_fu_76 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln43_9_fu_503_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal c_fu_80 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln41_fu_314_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten194_fu_84 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln41_fu_224_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln43_fu_152_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln43_fu_152_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_fu_170_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_174_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_497_fu_186_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_cast54_fu_182_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl16_cast_fu_192_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_498_fu_196_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln43_fu_152_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln45_fu_202_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal cmp9_i20_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp10_i21_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln41_1_fu_250_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln43_1_fu_260_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln43_1_fu_260_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln43_1_fu_260_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln48_fu_206_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln48_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln43_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln43_fu_242_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal and_ln43_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_1_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln43_fu_322_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_500_fu_354_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_mid_fu_358_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln43_2_fu_274_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln43_5_fu_366_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_501_fu_382_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_cast54_mid1_fu_378_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl16_cast_mid1_fu_388_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_mid1156_fu_392_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln43_1_fu_266_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln45_1_fu_398_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln48_3_fu_402_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln43_3_fu_282_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal cmp9_i20_mid1_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp10_i21_mid1_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln48_3_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_fu_438_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_4_fu_334_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp8_fu_442_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln43_5_cast_fu_374_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln48_2_fu_470_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln48_fu_476_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln43_6_fu_408_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln48_1_fu_480_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln43_1_fu_497_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln48_1_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln48_2_fu_544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal mul_ln43_1_fu_260_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln43_fu_152_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component inference_top_mul_3ns_9ns_10_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component inference_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_3ns_9ns_10_1_1_U26 : component inference_top_mul_3ns_9ns_10_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 9,
        dout_WIDTH => 10)
    port map (
        din0 => mul_ln43_fu_152_p0,
        din1 => mul_ln43_fu_152_p1,
        dout => mul_ln43_fu_152_p2);

    mul_3ns_9ns_10_1_1_U27 : component inference_top_mul_3ns_9ns_10_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 9,
        dout_WIDTH => 10)
    port map (
        din0 => mul_ln43_1_fu_260_p0,
        din1 => mul_ln43_1_fu_260_p1,
        dout => mul_ln43_1_fu_260_p2);

    flow_control_loop_pipe_sequential_init_U : component inference_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    c_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_80 <= ap_const_lv3_0;
                elsif (((icmp_ln41_fu_218_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    c_fu_80 <= select_ln41_fu_314_p3;
                end if;
            end if; 
        end if;
    end process;

    i_1_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_1_fu_68 <= ap_const_lv5_0;
                elsif (((icmp_ln41_fu_218_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_1_fu_68 <= add_ln45_fu_491_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten158_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten158_fu_76 <= ap_const_lv10_0;
                elsif (((icmp_ln41_fu_218_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten158_fu_76 <= select_ln43_9_fu_503_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten194_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten194_fu_84 <= ap_const_lv11_0;
                elsif (((icmp_ln41_fu_218_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten194_fu_84 <= add_ln41_fu_224_p2;
                end if;
            end if; 
        end if;
    end process;

    n_3_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    n_3_fu_72 <= ap_const_lv5_0;
                elsif (((icmp_ln41_fu_218_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    n_3_fu_72 <= select_ln43_8_fu_430_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln41_fu_218_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln46_reg_601 <= add_ln46_fu_452_p2;
                icmp_ln48_1_reg_611 <= icmp_ln48_1_fu_464_p2;
                icmp_ln48_reg_606 <= icmp_ln48_fu_458_p2;
                select_ln43_7_reg_596 <= select_ln43_7_fu_422_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    OutPadConv1_V_address0 <= zext_ln46_fu_536_p1(10 - 1 downto 0);

    OutPadConv1_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            OutPadConv1_V_ce0 <= ap_const_logic_1;
        else 
            OutPadConv1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    OutPadConv1_V_d0 <= 
        ap_const_lv16_0 when (or_ln48_2_fu_544_p2(0) = '1') else 
        pool_V_q0;

    OutPadConv1_V_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            OutPadConv1_V_we0 <= ap_const_logic_1;
        else 
            OutPadConv1_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln41_1_fu_250_p2 <= std_logic_vector(unsigned(c_fu_80) + unsigned(ap_const_lv3_1));
    add_ln41_fu_224_p2 <= std_logic_vector(unsigned(indvar_flatten194_fu_84) + unsigned(ap_const_lv11_1));
    add_ln43_1_fu_497_p2 <= std_logic_vector(unsigned(indvar_flatten158_fu_76) + unsigned(ap_const_lv10_1));
    add_ln43_fu_322_p2 <= std_logic_vector(unsigned(select_ln43_fu_242_p3) + unsigned(ap_const_lv5_1));
    add_ln45_fu_491_p2 <= std_logic_vector(unsigned(select_ln43_4_fu_334_p3) + unsigned(ap_const_lv5_1));
    add_ln46_fu_452_p2 <= std_logic_vector(unsigned(tmp8_fu_442_p4) + unsigned(select_ln43_5_cast_fu_374_p1));
    add_ln48_1_fu_480_p2 <= std_logic_vector(signed(sext_ln48_fu_476_p1) + signed(select_ln43_6_fu_408_p3));
    add_ln48_2_fu_470_p2 <= std_logic_vector(unsigned(select_ln43_4_fu_334_p3) + unsigned(ap_const_lv5_11));
    add_ln48_3_fu_402_p2 <= std_logic_vector(unsigned(select_ln43_1_fu_266_p3) + unsigned(sext_ln45_1_fu_398_p1));
    add_ln48_fu_206_p2 <= std_logic_vector(unsigned(mul_ln43_fu_152_p2) + unsigned(sext_ln45_fu_202_p1));
    and_ln43_fu_308_p2 <= (xor_ln43_fu_296_p2 and icmp_ln45_fu_302_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln41_fu_218_p2)
    begin
        if (((icmp_ln41_fu_218_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    cmp10_i21_fu_164_p2 <= "1" when (unsigned(n_3_fu_72) > unsigned(ap_const_lv5_E)) else "0";
    cmp10_i21_mid1_fu_348_p2 <= "1" when (unsigned(add_ln43_fu_322_p2) > unsigned(ap_const_lv5_E)) else "0";
    cmp9_i20_fu_158_p2 <= "1" when (n_3_fu_72 = ap_const_lv5_0) else "0";
    cmp9_i20_mid1_fu_342_p2 <= "1" when (add_ln43_fu_322_p2 = ap_const_lv5_0) else "0";
    empty_497_fu_186_p2 <= std_logic_vector(shift_left(unsigned(n_3_fu_72),to_integer(unsigned('0' & ap_const_lv5_1(5-1 downto 0)))));
    empty_498_fu_196_p2 <= std_logic_vector(unsigned(p_cast54_fu_182_p1) - unsigned(p_shl16_cast_fu_192_p1));
    empty_500_fu_354_p1 <= add_ln43_fu_322_p2(4 - 1 downto 0);
    empty_501_fu_382_p2 <= std_logic_vector(shift_left(unsigned(add_ln43_fu_322_p2),to_integer(unsigned('0' & ap_const_lv5_1(5-1 downto 0)))));
    empty_fu_170_p1 <= n_3_fu_72(4 - 1 downto 0);
    icmp_ln41_fu_218_p2 <= "1" when (indvar_flatten194_fu_84 = ap_const_lv11_400) else "0";
    icmp_ln43_fu_236_p2 <= "1" when (indvar_flatten158_fu_76 = ap_const_lv10_100) else "0";
    icmp_ln45_fu_302_p2 <= "1" when (i_1_fu_68 = ap_const_lv5_10) else "0";
    icmp_ln48_1_fu_464_p2 <= "1" when (unsigned(select_ln43_4_fu_334_p3) > unsigned(ap_const_lv5_E)) else "0";
    icmp_ln48_fu_458_p2 <= "1" when (select_ln43_4_fu_334_p3 = ap_const_lv5_0) else "0";
    mul_ln43_1_fu_260_p0 <= mul_ln43_1_fu_260_p00(3 - 1 downto 0);
    mul_ln43_1_fu_260_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln41_1_fu_250_p2),10));
    mul_ln43_1_fu_260_p1 <= ap_const_lv10_C4(9 - 1 downto 0);
    mul_ln43_fu_152_p0 <= mul_ln43_fu_152_p00(3 - 1 downto 0);
    mul_ln43_fu_152_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_fu_80),10));
    mul_ln43_fu_152_p1 <= ap_const_lv10_C4(9 - 1 downto 0);
    or_ln43_1_fu_328_p2 <= (icmp_ln43_fu_236_p2 or and_ln43_fu_308_p2);
    or_ln43_fu_290_p2 <= (or_ln48_fu_212_p2 or icmp_ln43_fu_236_p2);
    or_ln48_1_fu_540_p2 <= (icmp_ln48_reg_606 or icmp_ln48_1_reg_611);
    or_ln48_2_fu_544_p2 <= (select_ln43_7_reg_596 or or_ln48_1_fu_540_p2);
    or_ln48_3_fu_416_p2 <= (cmp9_i20_mid1_fu_342_p2 or cmp10_i21_mid1_fu_348_p2);
    or_ln48_fu_212_p2 <= (cmp9_i20_fu_158_p2 or cmp10_i21_fu_164_p2);
    p_cast54_fu_182_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_174_p3),9));
    p_cast54_mid1_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid_fu_358_p3),9));
    p_mid1156_fu_392_p2 <= std_logic_vector(unsigned(p_cast54_mid1_fu_378_p1) - unsigned(p_shl16_cast_mid1_fu_388_p1));
    p_mid_fu_358_p3 <= (empty_500_fu_354_p1 & ap_const_lv4_0);
    p_shl16_cast_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_497_fu_186_p2),9));
    p_shl16_cast_mid1_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_501_fu_382_p2),9));
    pool_V_address0 <= zext_ln48_fu_486_p1(10 - 1 downto 0);

    pool_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pool_V_ce0 <= ap_const_logic_1;
        else 
            pool_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln41_fu_314_p3 <= 
        add_ln41_1_fu_250_p2 when (icmp_ln43_fu_236_p2(0) = '1') else 
        c_fu_80;
    select_ln43_1_fu_266_p3 <= 
        mul_ln43_1_fu_260_p2 when (icmp_ln43_fu_236_p2(0) = '1') else 
        mul_ln43_fu_152_p2;
    select_ln43_2_fu_274_p3 <= 
        ap_const_lv8_0 when (icmp_ln43_fu_236_p2(0) = '1') else 
        tmp_s_fu_174_p3;
    select_ln43_3_fu_282_p3 <= 
        mul_ln43_1_fu_260_p2 when (icmp_ln43_fu_236_p2(0) = '1') else 
        add_ln48_fu_206_p2;
    select_ln43_4_fu_334_p3 <= 
        ap_const_lv5_0 when (or_ln43_1_fu_328_p2(0) = '1') else 
        i_1_fu_68;
    select_ln43_5_cast_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln43_5_fu_366_p3),10));
    select_ln43_5_fu_366_p3 <= 
        p_mid_fu_358_p3 when (and_ln43_fu_308_p2(0) = '1') else 
        select_ln43_2_fu_274_p3;
    select_ln43_6_fu_408_p3 <= 
        add_ln48_3_fu_402_p2 when (and_ln43_fu_308_p2(0) = '1') else 
        select_ln43_3_fu_282_p3;
    select_ln43_7_fu_422_p3 <= 
        or_ln48_3_fu_416_p2 when (and_ln43_fu_308_p2(0) = '1') else 
        or_ln43_fu_290_p2;
    select_ln43_8_fu_430_p3 <= 
        add_ln43_fu_322_p2 when (and_ln43_fu_308_p2(0) = '1') else 
        select_ln43_fu_242_p3;
    select_ln43_9_fu_503_p3 <= 
        ap_const_lv10_1 when (icmp_ln43_fu_236_p2(0) = '1') else 
        add_ln43_1_fu_497_p2;
    select_ln43_fu_242_p3 <= 
        ap_const_lv5_0 when (icmp_ln43_fu_236_p2(0) = '1') else 
        n_3_fu_72;
        sext_ln45_1_fu_398_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_mid1156_fu_392_p2),10));

        sext_ln45_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_498_fu_196_p2),10));

        sext_ln48_fu_476_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln48_2_fu_470_p2),10));

    tmp8_fu_442_p4 <= ((trunc_ln46_fu_438_p1 & ap_const_lv3_0) & select_ln43_4_fu_334_p3);
    tmp_s_fu_174_p3 <= (empty_fu_170_p1 & ap_const_lv4_0);
    trunc_ln46_fu_438_p1 <= select_ln41_fu_314_p3(2 - 1 downto 0);
    xor_ln43_fu_296_p2 <= (icmp_ln43_fu_236_p2 xor ap_const_lv1_1);
    zext_ln46_fu_536_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_reg_601),64));
    zext_ln48_fu_486_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln48_1_fu_480_p2),64));
end behav;
