-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference_top_D_CNN_Pipeline_loop_for_3_channel_pad_2_loop_for_channel_pad_2_loop_for_weight_p is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    OutPadConv2_V_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    OutPadConv2_V_ce0 : OUT STD_LOGIC;
    OutPadConv2_V_we0 : OUT STD_LOGIC;
    OutPadConv2_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    upsample_V_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    upsample_V_ce0 : OUT STD_LOGIC;
    upsample_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of inference_top_D_CNN_Pipeline_loop_for_3_channel_pad_2_loop_for_channel_pad_2_loop_for_weight_p is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv13_1C20 : STD_LOGIC_VECTOR (12 downto 0) := "1110000100000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv10_384 : STD_LOGIC_VECTOR (9 downto 0) := "1110000100";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv13_310 : STD_LOGIC_VECTOR (12 downto 0) := "0001100010000";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv6_23 : STD_LOGIC_VECTOR (5 downto 0) := "100011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv13_384 : STD_LOGIC_VECTOR (12 downto 0) := "0001110000100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln78_fu_151_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal c_2_reg_626 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_2_reg_626_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln78_reg_631 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln78_reg_631_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_fu_166_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_reg_635 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_reg_635_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_reg_635_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln78_1_fu_172_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln78_1_reg_646 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln78_1_reg_646_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_fu_267_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_reg_656 : STD_LOGIC_VECTOR (10 downto 0);
    signal and_ln78_fu_356_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln78_reg_661 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_mid1386_fu_417_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_mid1386_reg_666 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln80_3_fu_465_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln80_3_reg_671 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln85_fu_489_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln85_reg_681 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln85_1_fu_495_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln85_1_reg_686 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal zext_ln85_fu_517_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln83_fu_559_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_74 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln82_fu_522_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal n_fu_78 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln80_4_fu_473_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten390_fu_82 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln80_5_fu_196_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten390_load : STD_LOGIC_VECTOR (9 downto 0);
    signal c_fu_86 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln78_1_fu_178_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_c_2 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten442_fu_90 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln78_fu_157_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_sig_allocacmp_indvar_flatten442_load : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln80_1_fu_190_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln80_fu_225_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln80_fu_225_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl_fu_243_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl4_fu_255_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl27_cast_fu_251_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl28_cast_fu_263_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl5_fu_273_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl26_cast_fu_281_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_495_fu_285_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln80_fu_225_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln82_fu_291_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal cmp9_i146_fu_231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp10_i147_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln80_1_fu_320_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln80_1_fu_320_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln80_1_fu_320_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln85_fu_295_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_ln85_fu_301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln82_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln78_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln78_fu_310_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln80_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln80_fu_362_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl27_mid1_fu_393_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl28_mid1_fu_405_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl27_cast_mid1_fu_401_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl28_cast_mid1_fu_413_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl26_mid1_fu_423_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl26_cast_mid1_fu_431_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_mid1388_fu_435_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln78_2_fu_326_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln82_1_fu_441_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln85_3_fu_445_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln78_4_fu_333_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal cmp9_i146_mid1_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp10_i147_mid1_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln85_3_fu_459_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln78_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln80_fu_373_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_3_cast94_fu_481_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln85_2_fu_501_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln85_fu_507_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln80_2_fu_451_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln85_1_fu_511_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln78_3_fu_538_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln80_1_fu_544_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_582_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln80_1_cast_fu_550_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln83_fu_554_p2 : STD_LOGIC_VECTOR (12 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln83_fu_554_p2 : signal is "no";
    signal or_ln85_1_fu_564_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln85_2_fu_568_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_582_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_582_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_582_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_582_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_582_p20 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln80_1_fu_320_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln80_fu_225_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component inference_top_mul_4ns_11ns_13_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component inference_top_mac_muladd_4ns_10ns_5ns_13_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        din2 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component inference_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_4ns_11ns_13_1_1_U79 : component inference_top_mul_4ns_11ns_13_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 11,
        dout_WIDTH => 13)
    port map (
        din0 => mul_ln80_fu_225_p0,
        din1 => mul_ln80_fu_225_p1,
        dout => mul_ln80_fu_225_p2);

    mul_4ns_11ns_13_1_1_U80 : component inference_top_mul_4ns_11ns_13_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 11,
        dout_WIDTH => 13)
    port map (
        din0 => mul_ln80_1_fu_320_p0,
        din1 => mul_ln80_1_fu_320_p1,
        dout => mul_ln80_1_fu_320_p2);

    mac_muladd_4ns_10ns_5ns_13_4_1_U81 : component inference_top_mac_muladd_4ns_10ns_5ns_13_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 4,
        din1_WIDTH => 10,
        din2_WIDTH => 5,
        dout_WIDTH => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_582_p0,
        din1 => grp_fu_582_p1,
        din2 => grp_fu_582_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_582_p3);

    flow_control_loop_pipe_sequential_init_U : component inference_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    c_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln78_fu_151_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_86 <= select_ln78_1_fu_178_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_86 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    i_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    i_fu_74 <= ap_const_lv5_0;
                elsif (((icmp_ln78_reg_631_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    i_fu_74 <= add_ln82_fu_522_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten390_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln78_fu_151_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten390_fu_82 <= select_ln80_5_fu_196_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten390_fu_82 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten442_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln78_fu_151_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten442_fu_90 <= add_ln78_fu_157_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten442_fu_90 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    n_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    n_fu_78 <= ap_const_lv5_0;
                elsif (((icmp_ln78_reg_631_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    n_fu_78 <= select_ln80_4_fu_473_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln78_fu_151_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln78_1_reg_646 <= add_ln78_1_fu_172_p2;
                icmp_ln80_reg_635 <= icmp_ln80_fu_166_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln78_1_reg_646_pp0_iter1_reg <= add_ln78_1_reg_646;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                c_2_reg_626 <= ap_sig_allocacmp_c_2;
                c_2_reg_626_pp0_iter1_reg <= c_2_reg_626;
                icmp_ln78_reg_631 <= icmp_ln78_fu_151_p2;
                icmp_ln78_reg_631_pp0_iter1_reg <= icmp_ln78_reg_631;
                icmp_ln80_reg_635_pp0_iter1_reg <= icmp_ln80_reg_635;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln78_reg_631_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                and_ln78_reg_661 <= and_ln78_fu_356_p2;
                icmp_ln85_1_reg_686 <= icmp_ln85_1_fu_495_p2;
                icmp_ln85_reg_681 <= icmp_ln85_fu_489_p2;
                    p_mid1386_reg_666(10 downto 1) <= p_mid1386_fu_417_p2(10 downto 1);
                select_ln80_3_reg_671 <= select_ln80_3_fu_465_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln80_reg_635_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                    empty_reg_656(10 downto 1) <= empty_fu_267_p2(10 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln80_reg_635_pp0_iter2_reg <= icmp_ln80_reg_635_pp0_iter1_reg;
            end if;
        end if;
    end process;
    empty_reg_656(0) <= '0';
    p_mid1386_reg_666(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    OutPadConv2_V_address0 <= zext_ln83_fu_559_p1(13 - 1 downto 0);

    OutPadConv2_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            OutPadConv2_V_ce0 <= ap_const_logic_1;
        else 
            OutPadConv2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    OutPadConv2_V_d0 <= 
        ap_const_lv16_0 when (or_ln85_2_fu_568_p2(0) = '1') else 
        upsample_V_q0;

    OutPadConv2_V_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            OutPadConv2_V_we0 <= ap_const_logic_1;
        else 
            OutPadConv2_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln78_1_fu_172_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_c_2) + unsigned(ap_const_lv4_1));
    add_ln78_fu_157_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten442_load) + unsigned(ap_const_lv13_1));
    add_ln80_1_fu_190_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten390_load) + unsigned(ap_const_lv10_1));
    add_ln80_fu_362_p2 <= std_logic_vector(unsigned(select_ln78_fu_310_p3) + unsigned(ap_const_lv5_1));
    add_ln82_fu_522_p2 <= std_logic_vector(unsigned(select_ln80_fu_373_p3) + unsigned(ap_const_lv5_1));
    add_ln83_fu_554_p2 <= std_logic_vector(unsigned(grp_fu_582_p3) + unsigned(select_ln80_1_cast_fu_550_p1));
    add_ln85_1_fu_511_p2 <= std_logic_vector(signed(sext_ln85_fu_507_p1) + signed(select_ln80_2_fu_451_p3));
    add_ln85_2_fu_501_p2 <= std_logic_vector(unsigned(i_3_cast94_fu_481_p1) + unsigned(ap_const_lv6_23));
    add_ln85_3_fu_445_p2 <= std_logic_vector(unsigned(select_ln78_2_fu_326_p3) + unsigned(sext_ln82_1_fu_441_p1));
    add_ln85_fu_295_p2 <= std_logic_vector(unsigned(mul_ln80_fu_225_p2) + unsigned(sext_ln82_fu_291_p1));
    and_ln78_fu_356_p2 <= (xor_ln78_fu_345_p2 and icmp_ln82_fu_350_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln78_fu_151_p2)
    begin
        if (((icmp_ln78_fu_151_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, icmp_ln78_reg_631_pp0_iter1_reg)
    begin
        if (((icmp_ln78_reg_631_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, c_fu_86)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_c_2 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_c_2 <= c_fu_86;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten390_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten390_fu_82)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten390_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten390_load <= indvar_flatten390_fu_82;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten442_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten442_fu_90)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten442_load <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_indvar_flatten442_load <= indvar_flatten442_fu_90;
        end if; 
    end process;

    cmp10_i147_fu_237_p2 <= "1" when (unsigned(n_fu_78) > unsigned(ap_const_lv5_1C)) else "0";
    cmp10_i147_mid1_fu_387_p2 <= "1" when (unsigned(add_ln80_fu_362_p2) > unsigned(ap_const_lv5_1C)) else "0";
    cmp9_i146_fu_231_p2 <= "1" when (n_fu_78 = ap_const_lv5_0) else "0";
    cmp9_i146_mid1_fu_381_p2 <= "1" when (add_ln80_fu_362_p2 = ap_const_lv5_0) else "0";
    empty_495_fu_285_p2 <= std_logic_vector(unsigned(p_shl27_cast_fu_251_p1) - unsigned(p_shl26_cast_fu_281_p1));
    empty_fu_267_p2 <= std_logic_vector(unsigned(p_shl27_cast_fu_251_p1) - unsigned(p_shl28_cast_fu_263_p1));
    grp_fu_582_p0 <= grp_fu_582_p00(4 - 1 downto 0);
    grp_fu_582_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln78_1_fu_178_p3),13));
    grp_fu_582_p1 <= ap_const_lv13_384(10 - 1 downto 0);
    grp_fu_582_p2 <= grp_fu_582_p20(5 - 1 downto 0);
    grp_fu_582_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln80_fu_373_p3),13));
    i_3_cast94_fu_481_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln80_fu_373_p3),6));
    icmp_ln78_fu_151_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten442_load = ap_const_lv13_1C20) else "0";
    icmp_ln80_fu_166_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten390_load = ap_const_lv10_384) else "0";
    icmp_ln82_fu_350_p2 <= "1" when (i_fu_74 = ap_const_lv5_1E) else "0";
    icmp_ln85_1_fu_495_p2 <= "1" when (unsigned(select_ln80_fu_373_p3) > unsigned(ap_const_lv5_1C)) else "0";
    icmp_ln85_fu_489_p2 <= "1" when (select_ln80_fu_373_p3 = ap_const_lv5_0) else "0";
    mul_ln80_1_fu_320_p0 <= mul_ln80_1_fu_320_p00(4 - 1 downto 0);
    mul_ln80_1_fu_320_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln78_1_reg_646_pp0_iter1_reg),13));
    mul_ln80_1_fu_320_p1 <= ap_const_lv13_310(11 - 1 downto 0);
    mul_ln80_fu_225_p0 <= mul_ln80_fu_225_p00(4 - 1 downto 0);
    mul_ln80_fu_225_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_2_reg_626_pp0_iter1_reg),13));
    mul_ln80_fu_225_p1 <= ap_const_lv13_310(11 - 1 downto 0);
    or_ln78_fu_340_p2 <= (or_ln85_fu_301_p2 or icmp_ln80_reg_635_pp0_iter1_reg);
    or_ln80_fu_368_p2 <= (icmp_ln80_reg_635_pp0_iter1_reg or and_ln78_fu_356_p2);
    or_ln85_1_fu_564_p2 <= (icmp_ln85_reg_681 or icmp_ln85_1_reg_686);
    or_ln85_2_fu_568_p2 <= (select_ln80_3_reg_671 or or_ln85_1_fu_564_p2);
    or_ln85_3_fu_459_p2 <= (cmp9_i146_mid1_fu_381_p2 or cmp10_i147_mid1_fu_387_p2);
    or_ln85_fu_301_p2 <= (cmp9_i146_fu_231_p2 or cmp10_i147_fu_237_p2);
    p_mid1386_fu_417_p2 <= std_logic_vector(unsigned(p_shl27_cast_mid1_fu_401_p1) - unsigned(p_shl28_cast_mid1_fu_413_p1));
    p_mid1388_fu_435_p2 <= std_logic_vector(unsigned(p_shl27_cast_mid1_fu_401_p1) - unsigned(p_shl26_cast_mid1_fu_431_p1));
    p_shl26_cast_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl5_fu_273_p3),11));
    p_shl26_cast_mid1_fu_431_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl26_mid1_fu_423_p3),11));
    p_shl26_mid1_fu_423_p3 <= (add_ln80_fu_362_p2 & ap_const_lv2_0);
    p_shl27_cast_fu_251_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_fu_243_p3),11));
    p_shl27_cast_mid1_fu_401_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl27_mid1_fu_393_p3),11));
    p_shl27_mid1_fu_393_p3 <= (add_ln80_fu_362_p2 & ap_const_lv5_0);
    p_shl28_cast_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl4_fu_255_p3),11));
    p_shl28_cast_mid1_fu_413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl28_mid1_fu_405_p3),11));
    p_shl28_mid1_fu_405_p3 <= (add_ln80_fu_362_p2 & ap_const_lv1_0);
    p_shl4_fu_255_p3 <= (n_fu_78 & ap_const_lv1_0);
    p_shl5_fu_273_p3 <= (n_fu_78 & ap_const_lv2_0);
    p_shl_fu_243_p3 <= (n_fu_78 & ap_const_lv5_0);
    select_ln78_1_fu_178_p3 <= 
        add_ln78_1_fu_172_p2 when (icmp_ln80_fu_166_p2(0) = '1') else 
        ap_sig_allocacmp_c_2;
    select_ln78_2_fu_326_p3 <= 
        mul_ln80_1_fu_320_p2 when (icmp_ln80_reg_635_pp0_iter1_reg(0) = '1') else 
        mul_ln80_fu_225_p2;
    select_ln78_3_fu_538_p3 <= 
        ap_const_lv11_0 when (icmp_ln80_reg_635_pp0_iter2_reg(0) = '1') else 
        empty_reg_656;
    select_ln78_4_fu_333_p3 <= 
        mul_ln80_1_fu_320_p2 when (icmp_ln80_reg_635_pp0_iter1_reg(0) = '1') else 
        add_ln85_fu_295_p2;
    select_ln78_fu_310_p3 <= 
        ap_const_lv5_0 when (icmp_ln80_reg_635_pp0_iter1_reg(0) = '1') else 
        n_fu_78;
        select_ln80_1_cast_fu_550_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln80_1_fu_544_p3),13));

    select_ln80_1_fu_544_p3 <= 
        p_mid1386_reg_666 when (and_ln78_reg_661(0) = '1') else 
        select_ln78_3_fu_538_p3;
    select_ln80_2_fu_451_p3 <= 
        add_ln85_3_fu_445_p2 when (and_ln78_fu_356_p2(0) = '1') else 
        select_ln78_4_fu_333_p3;
    select_ln80_3_fu_465_p3 <= 
        or_ln85_3_fu_459_p2 when (and_ln78_fu_356_p2(0) = '1') else 
        or_ln78_fu_340_p2;
    select_ln80_4_fu_473_p3 <= 
        add_ln80_fu_362_p2 when (and_ln78_fu_356_p2(0) = '1') else 
        select_ln78_fu_310_p3;
    select_ln80_5_fu_196_p3 <= 
        ap_const_lv10_1 when (icmp_ln80_fu_166_p2(0) = '1') else 
        add_ln80_1_fu_190_p2;
    select_ln80_fu_373_p3 <= 
        ap_const_lv5_0 when (or_ln80_fu_368_p2(0) = '1') else 
        i_fu_74;
        sext_ln82_1_fu_441_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_mid1388_fu_435_p2),13));

        sext_ln82_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_495_fu_285_p2),13));

        sext_ln85_fu_507_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln85_2_fu_501_p2),13));

    upsample_V_address0 <= zext_ln85_fu_517_p1(13 - 1 downto 0);

    upsample_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            upsample_V_ce0 <= ap_const_logic_1;
        else 
            upsample_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln78_fu_345_p2 <= (icmp_ln80_reg_635_pp0_iter1_reg xor ap_const_lv1_1);
    zext_ln83_fu_559_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln83_fu_554_p2),64));
    zext_ln85_fu_517_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln85_1_fu_511_p2),64));
end behav;
