-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference_top_D_CNN_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_27_2_VITIS_LOOP_28_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    conv2_V_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    conv2_V_ce0 : OUT STD_LOGIC;
    conv2_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    upsample_V_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    upsample_V_ce0 : OUT STD_LOGIC;
    upsample_V_we0 : OUT STD_LOGIC;
    upsample_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of inference_top_D_CNN_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_27_2_VITIS_LOOP_28_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv13_1880 : STD_LOGIC_VECTOR (12 downto 0) := "1100010000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv10_310 : STD_LOGIC_VECTOR (9 downto 0) := "1100010000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv13_310 : STD_LOGIC_VECTOR (12 downto 0) := "0001100010000";
    constant ap_const_lv11_C4 : STD_LOGIC_VECTOR (10 downto 0) := "00011000100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln26_fu_151_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln26_reg_568 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_568_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_568_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_fu_169_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_reg_572 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_reg_572_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln27_reg_572_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_mid2376_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_mid2376_reg_591 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln29_1_fu_501_p2 : STD_LOGIC_VECTOR (12 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln29_1_fu_501_p2 : signal is "no";
    signal add_ln29_1_reg_613 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal zext_ln29_fu_496_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln29_2_fu_511_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_fu_76 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln28_fu_281_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal y_fu_80 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln27_3_fu_484_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten327_fu_84 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln27_4_fu_207_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten327_load : STD_LOGIC_VECTOR (9 downto 0);
    signal c_1_fu_88 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_mid2340_v_v_fu_181_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_c_1_load : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten377_fu_92 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln26_fu_157_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_sig_allocacmp_indvar_flatten377_load : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln26_1_fu_175_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_517_fu_193_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln27_1_fu_201_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln28_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten329_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln27_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_fu_255_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal div10_i_udiv_fu_267_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_295_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal div_i_udiv_fu_305_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl_fu_317_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl23_cast_fu_325_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal div_i_udiv_cast_fu_313_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl9_fu_335_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl10_fu_347_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl21_cast_fu_343_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl22_cast_fu_355_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul9_i_fu_329_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_fu_359_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal y_2_mid2337_fu_365_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln27_fu_386_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_72_fu_392_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal div_i_udiv_mid1_fu_402_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl23_mid1_fu_414_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl23_cast_mid1_fu_422_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal div_i_udiv_cast_mid1_fu_410_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul9_i_mid1_fu_426_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul9_i_cast_mid2362_fu_372_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln27_1_fu_432_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl21_mid1_fu_443_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl22_mid1_fu_455_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl21_cast_mid1_fu_451_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl22_cast_mid1_fu_463_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_mid1325_fu_467_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln28_1_mid2374_fu_379_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln27_2_fu_473_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_524_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln27_1_cast_fu_439_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln29_fu_491_p2 : STD_LOGIC_VECTOR (10 downto 0);
    attribute use_dsp48 of add_ln29_fu_491_p2 : signal is "no";
    signal grp_fu_515_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln27_2_cast_fu_480_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_515_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_515_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_515_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_524_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_524_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_524_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_515_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_515_p20 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_524_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_524_p20 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component inference_top_mac_muladd_4ns_10ns_5ns_13_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        din2 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component inference_top_mac_muladd_3ns_8ns_4ns_11_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component inference_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_4ns_10ns_5ns_13_4_1_U73 : component inference_top_mac_muladd_4ns_10ns_5ns_13_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 4,
        din1_WIDTH => 10,
        din2_WIDTH => 5,
        dout_WIDTH => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_515_p0,
        din1 => grp_fu_515_p1,
        din2 => grp_fu_515_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_515_p3);

    mac_muladd_3ns_8ns_4ns_11_4_1_U74 : component inference_top_mac_muladd_3ns_8ns_4ns_11_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 3,
        din1_WIDTH => 8,
        din2_WIDTH => 4,
        dout_WIDTH => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_524_p0,
        din1 => grp_fu_524_p1,
        din2 => grp_fu_524_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_524_p3);

    flow_control_loop_pipe_sequential_init_U : component inference_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    c_1_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln26_fu_151_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_1_fu_88 <= p_mid2340_v_v_fu_181_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_1_fu_88 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten327_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln26_fu_151_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten327_fu_84 <= select_ln27_4_fu_207_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten327_fu_84 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten377_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln26_fu_151_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten377_fu_92 <= add_ln26_fu_157_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten377_fu_92 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    x_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    x_fu_76 <= ap_const_lv5_0;
                elsif (((icmp_ln26_reg_568_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    x_fu_76 <= add_ln28_fu_281_p2;
                end if;
            end if; 
        end if;
    end process;

    y_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    y_fu_80 <= ap_const_lv5_0;
                elsif (((icmp_ln26_reg_568_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    y_fu_80 <= select_ln27_3_fu_484_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln26_reg_568_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln29_1_reg_613 <= add_ln29_1_fu_501_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln26_reg_568 <= icmp_ln26_fu_151_p2;
                icmp_ln26_reg_568_pp0_iter1_reg <= icmp_ln26_reg_568;
                icmp_ln27_reg_572_pp0_iter1_reg <= icmp_ln27_reg_572;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln26_reg_568_pp0_iter2_reg <= icmp_ln26_reg_568_pp0_iter1_reg;
                icmp_ln27_reg_572_pp0_iter2_reg <= icmp_ln27_reg_572_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln26_fu_151_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln27_reg_572 <= icmp_ln27_fu_169_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln26_reg_568_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln28_mid2376_reg_591 <= icmp_ln28_mid2376_fu_244_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln26_1_fu_175_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_c_1_load) + unsigned(ap_const_lv4_1));
    add_ln26_fu_157_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten377_load) + unsigned(ap_const_lv13_1));
    add_ln27_1_fu_201_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten327_load) + unsigned(ap_const_lv10_1));
    add_ln27_fu_386_p2 <= std_logic_vector(unsigned(y_2_mid2337_fu_365_p3) + unsigned(ap_const_lv5_1));
    add_ln28_fu_281_p2 <= std_logic_vector(unsigned(select_ln27_fu_255_p3) + unsigned(ap_const_lv5_1));
    add_ln29_1_fu_501_p2 <= std_logic_vector(unsigned(grp_fu_515_p3) + unsigned(select_ln27_2_cast_fu_480_p1));
    add_ln29_fu_491_p2 <= std_logic_vector(unsigned(grp_fu_524_p3) + unsigned(select_ln27_1_cast_fu_439_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln26_fu_151_p2)
    begin
        if (((icmp_ln26_fu_151_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone, icmp_ln26_reg_568_pp0_iter2_reg)
    begin
        if (((icmp_ln26_reg_568_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, c_1_fu_88)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_c_1_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_c_1_load <= c_1_fu_88;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten327_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten327_fu_84)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten327_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten327_load <= indvar_flatten327_fu_84;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten377_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten377_fu_92)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten377_load <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_indvar_flatten377_load <= indvar_flatten377_fu_92;
        end if; 
    end process;

    conv2_V_address0 <= zext_ln29_fu_496_p1(11 - 1 downto 0);

    conv2_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            conv2_V_ce0 <= ap_const_logic_1;
        else 
            conv2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    div10_i_udiv_fu_267_p4 <= select_ln27_fu_255_p3(4 downto 1);
    div_i_udiv_cast_fu_313_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(div_i_udiv_fu_305_p3),9));
    div_i_udiv_cast_mid1_fu_410_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(div_i_udiv_mid1_fu_402_p3),9));
    div_i_udiv_fu_305_p3 <= (tmp_s_fu_295_p4 & ap_const_lv1_0);
    div_i_udiv_mid1_fu_402_p3 <= (tmp_72_fu_392_p4 & ap_const_lv1_0);
    empty_517_fu_193_p1 <= p_mid2340_v_v_fu_181_p3(3 - 1 downto 0);
    empty_fu_359_p2 <= std_logic_vector(unsigned(p_shl21_cast_fu_343_p1) - unsigned(p_shl22_cast_fu_355_p1));
    grp_fu_515_p0 <= grp_fu_515_p00(4 - 1 downto 0);
    grp_fu_515_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid2340_v_v_fu_181_p3),13));
    grp_fu_515_p1 <= ap_const_lv13_310(10 - 1 downto 0);
    grp_fu_515_p2 <= grp_fu_515_p20(5 - 1 downto 0);
    grp_fu_515_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln27_fu_255_p3),13));
    grp_fu_524_p0 <= grp_fu_524_p00(3 - 1 downto 0);
    grp_fu_524_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_517_fu_193_p1),11));
    grp_fu_524_p1 <= ap_const_lv11_C4(8 - 1 downto 0);
    grp_fu_524_p2 <= grp_fu_524_p20(4 - 1 downto 0);
    grp_fu_524_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(div10_i_udiv_fu_267_p4),11));
    icmp_ln26_fu_151_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten377_load = ap_const_lv13_1880) else "0";
    icmp_ln27_fu_169_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten327_load = ap_const_lv10_310) else "0";
    icmp_ln28_fu_238_p2 <= "1" when (x_fu_76 = ap_const_lv5_1C) else "0";
    icmp_ln28_mid2376_fu_244_p2 <= (not_exitcond_flatten329_fu_233_p2 and icmp_ln28_fu_238_p2);
    mul9_i_cast_mid2362_fu_372_p3 <= 
        ap_const_lv9_0 when (icmp_ln27_reg_572_pp0_iter2_reg(0) = '1') else 
        mul9_i_fu_329_p2;
    mul9_i_fu_329_p2 <= std_logic_vector(unsigned(p_shl23_cast_fu_325_p1) - unsigned(div_i_udiv_cast_fu_313_p1));
    mul9_i_mid1_fu_426_p2 <= std_logic_vector(unsigned(p_shl23_cast_mid1_fu_422_p1) - unsigned(div_i_udiv_cast_mid1_fu_410_p1));
    not_exitcond_flatten329_fu_233_p2 <= (icmp_ln27_reg_572_pp0_iter1_reg xor ap_const_lv1_1);
    or_ln27_fu_250_p2 <= (icmp_ln28_mid2376_fu_244_p2 or icmp_ln27_reg_572_pp0_iter1_reg);
    p_mid1325_fu_467_p2 <= std_logic_vector(unsigned(p_shl21_cast_mid1_fu_451_p1) - unsigned(p_shl22_cast_mid1_fu_463_p1));
    p_mid2340_v_v_fu_181_p3 <= 
        add_ln26_1_fu_175_p2 when (icmp_ln27_fu_169_p2(0) = '1') else 
        ap_sig_allocacmp_c_1_load;
    p_shl10_fu_347_p3 <= (y_fu_80 & ap_const_lv2_0);
    p_shl21_cast_fu_343_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl9_fu_335_p3),11));
    p_shl21_cast_mid1_fu_451_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl21_mid1_fu_443_p3),11));
    p_shl21_mid1_fu_443_p3 <= (add_ln27_fu_386_p2 & ap_const_lv5_0);
    p_shl22_cast_fu_355_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl10_fu_347_p3),11));
    p_shl22_cast_mid1_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl22_mid1_fu_455_p3),11));
    p_shl22_mid1_fu_455_p3 <= (add_ln27_fu_386_p2 & ap_const_lv2_0);
    p_shl23_cast_fu_325_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_fu_317_p3),9));
    p_shl23_cast_mid1_fu_422_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl23_mid1_fu_414_p3),9));
    p_shl23_mid1_fu_414_p3 <= (tmp_72_fu_392_p4 & ap_const_lv4_0);
    p_shl9_fu_335_p3 <= (y_fu_80 & ap_const_lv5_0);
    p_shl_fu_317_p3 <= (tmp_s_fu_295_p4 & ap_const_lv4_0);
        select_ln27_1_cast_fu_439_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln27_1_fu_432_p3),11));

    select_ln27_1_fu_432_p3 <= 
        mul9_i_mid1_fu_426_p2 when (icmp_ln28_mid2376_reg_591(0) = '1') else 
        mul9_i_cast_mid2362_fu_372_p3;
        select_ln27_2_cast_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln27_2_fu_473_p3),13));

    select_ln27_2_fu_473_p3 <= 
        p_mid1325_fu_467_p2 when (icmp_ln28_mid2376_reg_591(0) = '1') else 
        sext_ln28_1_mid2374_fu_379_p3;
    select_ln27_3_fu_484_p3 <= 
        add_ln27_fu_386_p2 when (icmp_ln28_mid2376_reg_591(0) = '1') else 
        y_2_mid2337_fu_365_p3;
    select_ln27_4_fu_207_p3 <= 
        ap_const_lv10_1 when (icmp_ln27_fu_169_p2(0) = '1') else 
        add_ln27_1_fu_201_p2;
    select_ln27_fu_255_p3 <= 
        ap_const_lv5_0 when (or_ln27_fu_250_p2(0) = '1') else 
        x_fu_76;
    sext_ln28_1_mid2374_fu_379_p3 <= 
        ap_const_lv11_0 when (icmp_ln27_reg_572_pp0_iter2_reg(0) = '1') else 
        empty_fu_359_p2;
    tmp_72_fu_392_p4 <= add_ln27_fu_386_p2(4 downto 1);
    tmp_s_fu_295_p4 <= y_fu_80(4 downto 1);
    upsample_V_address0 <= zext_ln29_2_fu_511_p1(13 - 1 downto 0);

    upsample_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            upsample_V_ce0 <= ap_const_logic_1;
        else 
            upsample_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    upsample_V_d0 <= conv2_V_q0;

    upsample_V_we0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            upsample_V_we0 <= ap_const_logic_1;
        else 
            upsample_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    y_2_mid2337_fu_365_p3 <= 
        ap_const_lv5_0 when (icmp_ln27_reg_572_pp0_iter2_reg(0) = '1') else 
        y_fu_80;
    zext_ln29_2_fu_511_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_1_reg_613),64));
    zext_ln29_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_fu_491_p2),64));
end behav;
