// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inference_top_C_Dense_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_Dense_address0,
        input_Dense_ce0,
        input_Dense_q0,
        input_Dense_address1,
        input_Dense_ce1,
        input_Dense_q1,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        bias,
        weight,
        ap_return
);

parameter    ap_ST_fsm_state1 = 25'd1;
parameter    ap_ST_fsm_state2 = 25'd2;
parameter    ap_ST_fsm_state3 = 25'd4;
parameter    ap_ST_fsm_state4 = 25'd8;
parameter    ap_ST_fsm_state5 = 25'd16;
parameter    ap_ST_fsm_state6 = 25'd32;
parameter    ap_ST_fsm_state7 = 25'd64;
parameter    ap_ST_fsm_state8 = 25'd128;
parameter    ap_ST_fsm_state9 = 25'd256;
parameter    ap_ST_fsm_state10 = 25'd512;
parameter    ap_ST_fsm_state11 = 25'd1024;
parameter    ap_ST_fsm_state12 = 25'd2048;
parameter    ap_ST_fsm_state13 = 25'd4096;
parameter    ap_ST_fsm_state14 = 25'd8192;
parameter    ap_ST_fsm_state15 = 25'd16384;
parameter    ap_ST_fsm_state16 = 25'd32768;
parameter    ap_ST_fsm_state17 = 25'd65536;
parameter    ap_ST_fsm_state18 = 25'd131072;
parameter    ap_ST_fsm_state19 = 25'd262144;
parameter    ap_ST_fsm_state20 = 25'd524288;
parameter    ap_ST_fsm_state21 = 25'd1048576;
parameter    ap_ST_fsm_state22 = 25'd2097152;
parameter    ap_ST_fsm_state23 = 25'd4194304;
parameter    ap_ST_fsm_state24 = 25'd8388608;
parameter    ap_ST_fsm_state25 = 25'd16777216;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] input_Dense_address0;
output   input_Dense_ce0;
input  [14:0] input_Dense_q0;
output  [3:0] input_Dense_address1;
output   input_Dense_ce1;
input  [14:0] input_Dense_q1;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [15:0] m_axi_gmem1_WDATA;
output  [1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [15:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [9:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] bias;
input  [63:0] weight;
output  [15:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] input_Dense_address0;
reg input_Dense_ce0;
reg[3:0] input_Dense_address1;
reg input_Dense_ce1;
reg m_axi_gmem1_ARVALID;
reg m_axi_gmem1_RREADY;

(* fsm_encoding = "none" *) reg   [24:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [15:0] out_Dense_V_q0;
reg   [15:0] reg_344;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state22;
reg   [14:0] input_Dense_load_reg_395;
wire    ap_CS_fsm_state2;
reg   [14:0] input_Dense_load_1_reg_400;
reg   [14:0] input_Dense_load_2_reg_415;
wire    ap_CS_fsm_state3;
reg   [14:0] input_Dense_load_3_reg_420;
reg   [14:0] input_Dense_load_4_reg_435;
wire    ap_CS_fsm_state4;
reg   [14:0] input_Dense_load_5_reg_440;
reg   [14:0] input_Dense_load_6_reg_455;
wire    ap_CS_fsm_state5;
reg   [14:0] input_Dense_load_7_reg_460;
reg   [14:0] input_Dense_load_8_reg_475;
wire    ap_CS_fsm_state6;
reg   [14:0] input_Dense_load_9_reg_480;
reg   [14:0] input_Dense_load_10_reg_495;
wire    ap_CS_fsm_state7;
reg   [14:0] input_Dense_load_11_reg_500;
reg   [14:0] input_Dense_load_12_reg_515;
wire    ap_CS_fsm_state8;
reg   [14:0] input_Dense_load_13_reg_520;
wire    ap_CS_fsm_state9;
reg   [14:0] input_Dense_load_14_reg_545;
reg   [14:0] input_Dense_load_15_reg_550;
wire   [3:0] out_Dense_V_addr_reg_555;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state15;
reg   [3:0] out_Dense_V_address0;
reg    out_Dense_V_ce0;
reg    out_Dense_V_we0;
reg   [15:0] out_Dense_V_d0;
reg    out_Dense_V_ce1;
wire   [15:0] out_Dense_V_q1;
wire    grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_start;
wire    grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_done;
wire    grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_idle;
wire    grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_ready;
wire    grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWVALID;
wire   [63:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWADDR;
wire   [0:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWID;
wire   [31:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWLEN;
wire   [2:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWSIZE;
wire   [1:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWBURST;
wire   [1:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWLOCK;
wire   [3:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWCACHE;
wire   [2:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWPROT;
wire   [3:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWQOS;
wire   [3:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWREGION;
wire   [0:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWUSER;
wire    grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_WVALID;
wire   [15:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_WDATA;
wire   [1:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_WSTRB;
wire    grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_WLAST;
wire   [0:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_WID;
wire   [0:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_WUSER;
wire    grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARVALID;
wire   [63:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARADDR;
wire   [0:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARID;
wire   [31:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARLEN;
wire   [2:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARSIZE;
wire   [1:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARBURST;
wire   [1:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARLOCK;
wire   [3:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARCACHE;
wire   [2:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARPROT;
wire   [3:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARQOS;
wire   [3:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARREGION;
wire   [0:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARUSER;
wire    grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_RREADY;
wire    grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_BREADY;
wire   [3:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_out_Dense_V_address0;
wire    grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_out_Dense_V_ce0;
wire    grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_out_Dense_V_we0;
wire   [15:0] grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_out_Dense_V_d0;
wire    grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_start;
wire    grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_done;
wire    grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_idle;
wire    grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_ready;
wire   [3:0] grp_C_Dense_2_Pipeline_loop_detect_fu_304_out_Dense_V_address0;
wire    grp_C_Dense_2_Pipeline_loop_detect_fu_304_out_Dense_V_ce0;
wire   [3:0] grp_C_Dense_2_Pipeline_loop_detect_fu_304_maxindex_out;
wire    grp_C_Dense_2_Pipeline_loop_detect_fu_304_maxindex_out_ap_vld;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_start;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_done;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_idle;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_ready;
wire   [3:0] grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_out_Dense_V_address0;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_out_Dense_V_ce0;
wire   [15:0] grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_p_out;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_p_out_ap_vld;
wire   [16:0] grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_grp_exp_17_9_s_fu_568_p_din1;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_grp_exp_17_9_s_fu_568_p_start;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_start;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_done;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_idle;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_ready;
wire   [3:0] grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_address0;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_ce0;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_we0;
wire   [15:0] grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_d0;
wire   [3:0] grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_address1;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_ce1;
wire   [16:0] grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_grp_exp_17_9_s_fu_568_p_din1;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_grp_exp_17_9_s_fu_568_p_start;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_start;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_done;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_idle;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_ready;
wire   [3:0] grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_out_Dense_V_address0;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_out_Dense_V_ce0;
wire   [15:0] grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_maxindex_2_V_out;
wire    grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_maxindex_2_V_out_ap_vld;
reg    grp_exp_17_9_s_fu_568_ap_start;
wire    grp_exp_17_9_s_fu_568_ap_done;
wire    grp_exp_17_9_s_fu_568_ap_idle;
wire    grp_exp_17_9_s_fu_568_ap_ready;
reg   [16:0] grp_exp_17_9_s_fu_568_x;
wire   [16:0] grp_exp_17_9_s_fu_568_ap_return;
reg    grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
reg   [3:0] maxindex_loc_fu_82;
reg    grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_start_reg;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
reg    grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_start_reg;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
reg    grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_start_reg;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire   [63:0] idxprom40_fu_355_p1;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state21;
reg   [24:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 25'd1;
#0 grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_start_reg = 1'b0;
#0 grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_start_reg = 1'b0;
#0 grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_start_reg = 1'b0;
#0 grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_start_reg = 1'b0;
#0 grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_start_reg = 1'b0;
end

inference_top_C_Dense_2_out_Dense_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
out_Dense_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_Dense_V_address0),
    .ce0(out_Dense_V_ce0),
    .we0(out_Dense_V_we0),
    .d0(out_Dense_V_d0),
    .q0(out_Dense_V_q0),
    .address1(grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_address1),
    .ce1(out_Dense_V_ce1),
    .q1(out_Dense_V_q1)
);

inference_top_C_Dense_2_Pipeline_loop_for_a_Dense_2 grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_start),
    .ap_done(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_done),
    .ap_idle(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_idle),
    .ap_ready(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_ready),
    .m_axi_gmem1_AWVALID(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(m_axi_gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(m_axi_gmem1_RVALID),
    .m_axi_gmem1_RREADY(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(m_axi_gmem1_RDATA),
    .m_axi_gmem1_RLAST(m_axi_gmem1_RLAST),
    .m_axi_gmem1_RID(m_axi_gmem1_RID),
    .m_axi_gmem1_RFIFONUM(m_axi_gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(m_axi_gmem1_RUSER),
    .m_axi_gmem1_RRESP(m_axi_gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .weight(weight),
    .zext_ln818(input_Dense_load_reg_395),
    .zext_ln1347(input_Dense_load_1_reg_400),
    .zext_ln1347_1(input_Dense_load_2_reg_415),
    .zext_ln1347_2(input_Dense_load_3_reg_420),
    .zext_ln1347_3(input_Dense_load_4_reg_435),
    .zext_ln1347_4(input_Dense_load_5_reg_440),
    .zext_ln1347_5(input_Dense_load_6_reg_455),
    .zext_ln1347_6(input_Dense_load_7_reg_460),
    .zext_ln1347_7(input_Dense_load_8_reg_475),
    .zext_ln1347_8(input_Dense_load_9_reg_480),
    .zext_ln1347_9(input_Dense_load_10_reg_495),
    .zext_ln1347_10(input_Dense_load_11_reg_500),
    .zext_ln1347_11(input_Dense_load_12_reg_515),
    .zext_ln1347_12(input_Dense_load_13_reg_520),
    .zext_ln1347_13(input_Dense_load_14_reg_545),
    .zext_ln1347_14(input_Dense_load_15_reg_550),
    .bias(bias),
    .out_Dense_V_address0(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_out_Dense_V_address0),
    .out_Dense_V_ce0(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_out_Dense_V_ce0),
    .out_Dense_V_we0(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_out_Dense_V_we0),
    .out_Dense_V_d0(grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_out_Dense_V_d0)
);

inference_top_C_Dense_2_Pipeline_loop_detect grp_C_Dense_2_Pipeline_loop_detect_fu_304(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_start),
    .ap_done(grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_done),
    .ap_idle(grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_idle),
    .ap_ready(grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_ready),
    .max_V(reg_344),
    .out_Dense_V_address0(grp_C_Dense_2_Pipeline_loop_detect_fu_304_out_Dense_V_address0),
    .out_Dense_V_ce0(grp_C_Dense_2_Pipeline_loop_detect_fu_304_out_Dense_V_ce0),
    .out_Dense_V_q0(out_Dense_V_q0),
    .maxindex_out(grp_C_Dense_2_Pipeline_loop_detect_fu_304_maxindex_out),
    .maxindex_out_ap_vld(grp_C_Dense_2_Pipeline_loop_detect_fu_304_maxindex_out_ap_vld)
);

inference_top_C_Dense_2_Pipeline_VITIS_LOOP_53_1 grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_start),
    .ap_done(grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_done),
    .ap_idle(grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_idle),
    .ap_ready(grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_ready),
    .out_Dense_V_address0(grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_out_Dense_V_address0),
    .out_Dense_V_ce0(grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_out_Dense_V_ce0),
    .out_Dense_V_q0(out_Dense_V_q0),
    .sext_ln813_3(reg_344),
    .p_out(grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_p_out),
    .p_out_ap_vld(grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_p_out_ap_vld),
    .grp_exp_17_9_s_fu_568_p_din1(grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_grp_exp_17_9_s_fu_568_p_din1),
    .grp_exp_17_9_s_fu_568_p_dout0(grp_exp_17_9_s_fu_568_ap_return),
    .grp_exp_17_9_s_fu_568_p_start(grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_grp_exp_17_9_s_fu_568_p_start),
    .grp_exp_17_9_s_fu_568_p_ready(grp_exp_17_9_s_fu_568_ap_ready),
    .grp_exp_17_9_s_fu_568_p_done(grp_exp_17_9_s_fu_568_ap_done),
    .grp_exp_17_9_s_fu_568_p_idle(grp_exp_17_9_s_fu_568_ap_idle)
);

inference_top_C_Dense_2_Pipeline_VITIS_LOOP_57_2 grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_start),
    .ap_done(grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_done),
    .ap_idle(grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_idle),
    .ap_ready(grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_ready),
    .out_Dense_V_address0(grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_address0),
    .out_Dense_V_ce0(grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_ce0),
    .out_Dense_V_we0(grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_we0),
    .out_Dense_V_d0(grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_d0),
    .out_Dense_V_address1(grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_address1),
    .out_Dense_V_ce1(grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_ce1),
    .out_Dense_V_q1(out_Dense_V_q1),
    .sext_ln813_3(reg_344),
    .p_cast(grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_p_out),
    .grp_exp_17_9_s_fu_568_p_din1(grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_grp_exp_17_9_s_fu_568_p_din1),
    .grp_exp_17_9_s_fu_568_p_dout0(grp_exp_17_9_s_fu_568_ap_return),
    .grp_exp_17_9_s_fu_568_p_start(grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_grp_exp_17_9_s_fu_568_p_start),
    .grp_exp_17_9_s_fu_568_p_ready(grp_exp_17_9_s_fu_568_ap_ready),
    .grp_exp_17_9_s_fu_568_p_done(grp_exp_17_9_s_fu_568_ap_done),
    .grp_exp_17_9_s_fu_568_p_idle(grp_exp_17_9_s_fu_568_ap_idle)
);

inference_top_C_Dense_2_Pipeline_VITIS_LOOP_62_3 grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_start),
    .ap_done(grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_done),
    .ap_idle(grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_idle),
    .ap_ready(grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_ready),
    .max_2_V(reg_344),
    .out_Dense_V_address0(grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_out_Dense_V_address0),
    .out_Dense_V_ce0(grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_out_Dense_V_ce0),
    .out_Dense_V_q0(out_Dense_V_q0),
    .maxindex_2_V_out(grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_maxindex_2_V_out),
    .maxindex_2_V_out_ap_vld(grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_maxindex_2_V_out_ap_vld)
);

inference_top_exp_17_9_s grp_exp_17_9_s_fu_568(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_exp_17_9_s_fu_568_ap_start),
    .ap_done(grp_exp_17_9_s_fu_568_ap_done),
    .ap_idle(grp_exp_17_9_s_fu_568_ap_idle),
    .ap_ready(grp_exp_17_9_s_fu_568_ap_ready),
    .x(grp_exp_17_9_s_fu_568_x),
    .ap_return(grp_exp_17_9_s_fu_568_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_start_reg <= 1'b1;
        end else if ((grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_ready == 1'b1)) begin
            grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state19)) begin
            grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_start_reg <= 1'b1;
        end else if ((grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_ready == 1'b1)) begin
            grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state23)) begin
            grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_start_reg <= 1'b1;
        end else if ((grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_ready == 1'b1)) begin
            grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_start_reg <= 1'b1;
        end else if ((grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_ready == 1'b1)) begin
            grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_start_reg <= 1'b1;
        end else if ((grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_ready == 1'b1)) begin
            grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        input_Dense_load_10_reg_495 <= input_Dense_q1;
        input_Dense_load_11_reg_500 <= input_Dense_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        input_Dense_load_12_reg_515 <= input_Dense_q1;
        input_Dense_load_13_reg_520 <= input_Dense_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        input_Dense_load_14_reg_545 <= input_Dense_q1;
        input_Dense_load_15_reg_550 <= input_Dense_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_Dense_load_1_reg_400 <= input_Dense_q0;
        input_Dense_load_reg_395 <= input_Dense_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_Dense_load_2_reg_415 <= input_Dense_q1;
        input_Dense_load_3_reg_420 <= input_Dense_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_Dense_load_4_reg_435 <= input_Dense_q1;
        input_Dense_load_5_reg_440 <= input_Dense_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_Dense_load_6_reg_455 <= input_Dense_q1;
        input_Dense_load_7_reg_460 <= input_Dense_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_Dense_load_8_reg_475 <= input_Dense_q1;
        input_Dense_load_9_reg_480 <= input_Dense_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_C_Dense_2_Pipeline_loop_detect_fu_304_maxindex_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        maxindex_loc_fu_82 <= grp_C_Dense_2_Pipeline_loop_detect_fu_304_maxindex_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12))) begin
        reg_344 <= out_Dense_V_q0;
    end
end

always @ (*) begin
    if ((grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_done == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

always @ (*) begin
    if ((grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_done == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_exp_17_9_s_fu_568_ap_start = grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_grp_exp_17_9_s_fu_568_p_start;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_exp_17_9_s_fu_568_ap_start = grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_grp_exp_17_9_s_fu_568_p_start;
    end else begin
        grp_exp_17_9_s_fu_568_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_exp_17_9_s_fu_568_x = grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_grp_exp_17_9_s_fu_568_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_exp_17_9_s_fu_568_x = grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_grp_exp_17_9_s_fu_568_p_din1;
    end else begin
        grp_exp_17_9_s_fu_568_x = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        input_Dense_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        input_Dense_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        input_Dense_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        input_Dense_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_Dense_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_Dense_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_Dense_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        input_Dense_address0 = 64'd1;
    end else begin
        input_Dense_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        input_Dense_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        input_Dense_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        input_Dense_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        input_Dense_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_Dense_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_Dense_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_Dense_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        input_Dense_address1 = 64'd0;
    end else begin
        input_Dense_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        input_Dense_ce0 = 1'b1;
    end else begin
        input_Dense_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        input_Dense_ce1 = 1'b1;
    end else begin
        input_Dense_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem1_ARVALID = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARVALID;
    end else begin
        m_axi_gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem1_RREADY = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_RREADY;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        out_Dense_V_address0 = out_Dense_V_addr_reg_555;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        out_Dense_V_address0 = idxprom40_fu_355_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        out_Dense_V_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        out_Dense_V_address0 = grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_out_Dense_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        out_Dense_V_address0 = grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        out_Dense_V_address0 = grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_out_Dense_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        out_Dense_V_address0 = grp_C_Dense_2_Pipeline_loop_detect_fu_304_out_Dense_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        out_Dense_V_address0 = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_out_Dense_V_address0;
    end else begin
        out_Dense_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state11))) begin
        out_Dense_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        out_Dense_V_ce0 = grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_out_Dense_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        out_Dense_V_ce0 = grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        out_Dense_V_ce0 = grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_out_Dense_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        out_Dense_V_ce0 = grp_C_Dense_2_Pipeline_loop_detect_fu_304_out_Dense_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        out_Dense_V_ce0 = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_out_Dense_V_ce0;
    end else begin
        out_Dense_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        out_Dense_V_ce1 = grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_ce1;
    end else begin
        out_Dense_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        out_Dense_V_d0 = grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        out_Dense_V_d0 = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_out_Dense_V_d0;
    end else begin
        out_Dense_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        out_Dense_V_we0 = grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_out_Dense_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        out_Dense_V_we0 = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_out_Dense_V_we0;
    end else begin
        out_Dense_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_maxindex_2_V_out;

assign grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_start = grp_C_Dense_2_Pipeline_VITIS_LOOP_53_1_fu_311_ap_start_reg;

assign grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_start = grp_C_Dense_2_Pipeline_VITIS_LOOP_57_2_fu_324_ap_start_reg;

assign grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_start = grp_C_Dense_2_Pipeline_VITIS_LOOP_62_3_fu_337_ap_start_reg;

assign grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_start = grp_C_Dense_2_Pipeline_loop_detect_fu_304_ap_start_reg;

assign grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_start = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_ap_start_reg;

assign idxprom40_fu_355_p1 = maxindex_loc_fu_82;

assign m_axi_gmem1_ARADDR = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARADDR;

assign m_axi_gmem1_ARBURST = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARBURST;

assign m_axi_gmem1_ARCACHE = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARCACHE;

assign m_axi_gmem1_ARID = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARID;

assign m_axi_gmem1_ARLEN = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARLEN;

assign m_axi_gmem1_ARLOCK = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARLOCK;

assign m_axi_gmem1_ARPROT = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARPROT;

assign m_axi_gmem1_ARQOS = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARQOS;

assign m_axi_gmem1_ARREGION = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARREGION;

assign m_axi_gmem1_ARSIZE = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARSIZE;

assign m_axi_gmem1_ARUSER = grp_C_Dense_2_Pipeline_loop_for_a_Dense_2_fu_275_m_axi_gmem1_ARUSER;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 16'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 2'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign out_Dense_V_addr_reg_555 = 64'd0;

endmodule //inference_top_C_Dense_2
