-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference_top_D_CNN_Pipeline_VITIS_LOOP_6_1_VITIS_LOOP_8_2_VITIS_LOOP_9_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    conv1_V_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv1_V_ce0 : OUT STD_LOGIC;
    conv1_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    conv1_V_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv1_V_ce1 : OUT STD_LOGIC;
    conv1_V_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    conv1_V_address2 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv1_V_ce2 : OUT STD_LOGIC;
    conv1_V_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
    conv1_V_address3 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv1_V_ce3 : OUT STD_LOGIC;
    conv1_V_q3 : IN STD_LOGIC_VECTOR (15 downto 0);
    pool_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pool_V_ce0 : OUT STD_LOGIC;
    pool_V_we0 : OUT STD_LOGIC;
    pool_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of inference_top_D_CNN_Pipeline_VITIS_LOOP_6_1_VITIS_LOOP_8_2_VITIS_LOOP_9_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_310 : STD_LOGIC_VECTOR (9 downto 0) := "1100010000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv8_C4 : STD_LOGIC_VECTOR (7 downto 0) := "11000100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv12_1C : STD_LOGIC_VECTOR (11 downto 0) := "000000011100";
    constant ap_const_lv12_1D : STD_LOGIC_VECTOR (11 downto 0) := "000000011101";
    constant ap_const_lv8_E : STD_LOGIC_VECTOR (7 downto 0) := "00001110";
    constant ap_const_lv16_F600 : STD_LOGIC_VECTOR (15 downto 0) := "1111011000000000";
    constant ap_const_lv12_310 : STD_LOGIC_VECTOR (11 downto 0) := "001100010000";
    constant ap_const_lv10_C4 : STD_LOGIC_VECTOR (9 downto 0) := "0011000100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln6_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln6_reg_690 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln6_reg_690_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln6_reg_690_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_fu_224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_694 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_694_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_694_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_694_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln8_3_fu_236_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln8_3_reg_704 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln8_3_reg_704_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal and_ln8_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln8_reg_719 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln8_reg_719_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln15_3_fu_595_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln15_3_reg_757 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal zext_ln14_fu_442_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln14_1_fu_453_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_2_fu_464_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln14_3_fu_475_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln19_fu_619_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal y_fu_78 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln9_1_fu_325_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal index_1_fu_82 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln20_fu_603_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal z_fu_86 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln8_9_fu_430_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal index_fu_90 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln8_8_fu_518_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten112_fu_94 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln8_10_fu_254_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten112_load : STD_LOGIC_VECTOR (7 downto 0);
    signal i_fu_98 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten145_fu_102 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln6_fu_212_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten145_load : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln6_1_fu_230_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln8_2_fu_248_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln9_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln8_fu_283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln8_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln8_6_fu_305_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_313_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl1_fu_339_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl9_fu_351_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl11_cast_fu_347_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl12_cast_fu_359_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_fu_363_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln8_1_fu_369_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln8_fu_383_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl11_mid1_fu_389_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl12_mid1_fu_401_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl11_cast_mid1_fu_397_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl12_cast_mid1_fu_409_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_mid1110_fu_413_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln8_4_fu_376_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln8_7_fu_419_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_623_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln8_8_cast_fu_426_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln13_fu_437_p2 : STD_LOGIC_VECTOR (11 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln13_fu_437_p2 : signal is "no";
    signal or_ln13_fu_447_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln13_1_fu_458_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln13_2_fu_469_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln8_fu_491_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln8_1_fu_505_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln8_2_fu_498_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln8_5_fu_511_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1651_fu_529_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln15_fu_535_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1651_1_fu_543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1651_fu_549_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln15_1_fu_555_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1651_2_fu_563_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1651_1_fu_569_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln15_2_fu_575_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1651_3_fu_583_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1651_2_fu_589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_632_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_623_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_623_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_623_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_632_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_632_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_632_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_623_p00 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_623_p20 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_632_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_632_p20 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component inference_top_mac_muladd_3ns_10ns_5ns_12_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        din2 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component inference_top_mac_muladd_3ns_8ns_8ns_10_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component inference_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_3ns_10ns_5ns_12_4_1_U21 : component inference_top_mac_muladd_3ns_10ns_5ns_12_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 3,
        din1_WIDTH => 10,
        din2_WIDTH => 5,
        dout_WIDTH => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_623_p0,
        din1 => grp_fu_623_p1,
        din2 => grp_fu_623_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_623_p3);

    mac_muladd_3ns_8ns_8ns_10_4_1_U22 : component inference_top_mac_muladd_3ns_8ns_8ns_10_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 3,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        dout_WIDTH => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_632_p0,
        din1 => grp_fu_632_p1,
        din2 => grp_fu_632_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_632_p3);

    flow_control_loop_pipe_sequential_init_U : component inference_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    i_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln6_fu_206_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_98 <= select_ln8_3_fu_236_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_98 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    index_1_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    index_1_fu_82 <= ap_const_lv8_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    index_1_fu_82 <= add_ln20_fu_603_p2;
                end if;
            end if; 
        end if;
    end process;

    index_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    index_fu_90 <= ap_const_lv8_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    index_fu_90 <= select_ln8_8_fu_518_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten112_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln6_fu_206_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten112_fu_94 <= select_ln8_10_fu_254_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten112_fu_94 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten145_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln6_fu_206_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten145_fu_102 <= add_ln6_fu_212_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten145_fu_102 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    y_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    y_fu_78 <= ap_const_lv4_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln6_reg_690_pp0_iter1_reg = ap_const_lv1_0))) then 
                    y_fu_78 <= add_ln9_1_fu_325_p2;
                end if;
            end if; 
        end if;
    end process;

    z_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    z_fu_86 <= ap_const_lv4_0;
                elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln6_reg_690_pp0_iter2_reg = ap_const_lv1_0))) then 
                    z_fu_86 <= select_ln8_9_fu_430_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln6_reg_690_pp0_iter1_reg = ap_const_lv1_0))) then
                and_ln8_reg_719 <= and_ln8_fu_294_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln8_reg_719_pp0_iter3_reg <= and_ln8_reg_719;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                icmp_ln6_reg_690_pp0_iter2_reg <= icmp_ln6_reg_690_pp0_iter1_reg;
                icmp_ln8_reg_694_pp0_iter2_reg <= icmp_ln8_reg_694_pp0_iter1_reg;
                icmp_ln8_reg_694_pp0_iter3_reg <= icmp_ln8_reg_694_pp0_iter2_reg;
                select_ln15_3_reg_757 <= select_ln15_3_fu_595_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln6_reg_690 <= icmp_ln6_fu_206_p2;
                icmp_ln6_reg_690_pp0_iter1_reg <= icmp_ln6_reg_690;
                icmp_ln8_reg_694_pp0_iter1_reg <= icmp_ln8_reg_694;
                select_ln8_3_reg_704_pp0_iter1_reg <= select_ln8_3_reg_704;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln6_fu_206_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln8_reg_694 <= icmp_ln8_fu_224_p2;
                select_ln8_3_reg_704 <= select_ln8_3_fu_236_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln13_1_fu_458_p2 <= std_logic_vector(unsigned(add_ln13_fu_437_p2) + unsigned(ap_const_lv12_1C));
    add_ln13_2_fu_469_p2 <= std_logic_vector(unsigned(add_ln13_fu_437_p2) + unsigned(ap_const_lv12_1D));
    add_ln13_fu_437_p2 <= std_logic_vector(unsigned(grp_fu_623_p3) + unsigned(select_ln8_8_cast_fu_426_p1));
    add_ln20_fu_603_p2 <= std_logic_vector(unsigned(select_ln8_5_fu_511_p3) + unsigned(ap_const_lv8_1));
    add_ln6_1_fu_230_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv3_1));
    add_ln6_fu_212_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten145_load) + unsigned(ap_const_lv10_1));
    add_ln8_1_fu_505_p2 <= std_logic_vector(unsigned(select_ln8_fu_491_p3) + unsigned(ap_const_lv8_E));
    add_ln8_2_fu_248_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten112_load) + unsigned(ap_const_lv8_1));
    add_ln8_fu_383_p2 <= std_logic_vector(unsigned(select_ln8_1_fu_369_p3) + unsigned(ap_const_lv4_1));
    add_ln9_1_fu_325_p2 <= std_logic_vector(unsigned(select_ln8_6_fu_305_p3) + unsigned(ap_const_lv4_1));
    and_ln8_fu_294_p2 <= (xor_ln8_fu_283_p2 and icmp_ln9_fu_288_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln6_fu_206_p2)
    begin
        if (((icmp_ln6_fu_206_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone, icmp_ln6_reg_690_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln6_reg_690_pp0_iter2_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_98)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_98;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten112_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten112_fu_94)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten112_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten112_load <= indvar_flatten112_fu_94;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten145_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten145_fu_102)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten145_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten145_load <= indvar_flatten145_fu_102;
        end if; 
    end process;

    conv1_V_address0 <= zext_ln14_3_fu_475_p1(12 - 1 downto 0);
    conv1_V_address1 <= zext_ln14_2_fu_464_p1(12 - 1 downto 0);
    conv1_V_address2 <= zext_ln14_1_fu_453_p1(12 - 1 downto 0);
    conv1_V_address3 <= zext_ln14_fu_442_p1(12 - 1 downto 0);

    conv1_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            conv1_V_ce0 <= ap_const_logic_1;
        else 
            conv1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    conv1_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            conv1_V_ce1 <= ap_const_logic_1;
        else 
            conv1_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    conv1_V_ce2_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            conv1_V_ce2 <= ap_const_logic_1;
        else 
            conv1_V_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    conv1_V_ce3_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            conv1_V_ce3 <= ap_const_logic_1;
        else 
            conv1_V_ce3 <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_363_p2 <= std_logic_vector(unsigned(p_shl11_cast_fu_347_p1) - unsigned(p_shl12_cast_fu_359_p1));
    grp_fu_623_p0 <= grp_fu_623_p00(3 - 1 downto 0);
    grp_fu_623_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln8_3_fu_236_p3),12));
    grp_fu_623_p1 <= ap_const_lv12_310(10 - 1 downto 0);
    grp_fu_623_p2 <= grp_fu_623_p20(5 - 1 downto 0);
    grp_fu_623_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_313_p3),12));
    grp_fu_632_p0 <= grp_fu_632_p00(3 - 1 downto 0);
    grp_fu_632_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln8_3_reg_704_pp0_iter1_reg),10));
    grp_fu_632_p1 <= ap_const_lv10_C4(8 - 1 downto 0);
    grp_fu_632_p2 <= grp_fu_632_p20(8 - 1 downto 0);
    grp_fu_632_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln8_5_fu_511_p3),10));
    icmp_ln1651_1_fu_543_p2 <= "1" when (signed(conv1_V_q2) < signed(select_ln15_fu_535_p3)) else "0";
    icmp_ln1651_2_fu_563_p2 <= "1" when (signed(conv1_V_q1) < signed(select_ln15_1_fu_555_p3)) else "0";
    icmp_ln1651_3_fu_583_p2 <= "1" when (signed(conv1_V_q0) < signed(select_ln15_2_fu_575_p3)) else "0";
    icmp_ln1651_fu_529_p2 <= "1" when (signed(conv1_V_q3) < signed(ap_const_lv16_F600)) else "0";
    icmp_ln6_fu_206_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten145_load = ap_const_lv10_310) else "0";
    icmp_ln8_fu_224_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten112_load = ap_const_lv8_C4) else "0";
    icmp_ln9_fu_288_p2 <= "1" when (y_fu_78 = ap_const_lv4_E) else "0";
    or_ln13_fu_447_p2 <= (ap_const_lv12_1 or add_ln13_fu_437_p2);
    or_ln8_fu_300_p2 <= (icmp_ln8_reg_694_pp0_iter1_reg or and_ln8_fu_294_p2);
    p_mid1110_fu_413_p2 <= std_logic_vector(unsigned(p_shl11_cast_mid1_fu_397_p1) - unsigned(p_shl12_cast_mid1_fu_409_p1));
    p_shl11_cast_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl1_fu_339_p3),11));
    p_shl11_cast_mid1_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl11_mid1_fu_389_p3),11));
    p_shl11_mid1_fu_389_p3 <= (add_ln8_fu_383_p2 & ap_const_lv6_0);
    p_shl12_cast_fu_359_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl9_fu_351_p3),11));
    p_shl12_cast_mid1_fu_409_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl12_mid1_fu_401_p3),11));
    p_shl12_mid1_fu_401_p3 <= (add_ln8_fu_383_p2 & ap_const_lv3_0);
    p_shl1_fu_339_p3 <= (z_fu_86 & ap_const_lv6_0);
    p_shl9_fu_351_p3 <= (z_fu_86 & ap_const_lv3_0);
    pool_V_address0 <= zext_ln19_fu_619_p1(10 - 1 downto 0);

    pool_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pool_V_ce0 <= ap_const_logic_1;
        else 
            pool_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    pool_V_d0 <= select_ln15_3_reg_757;

    pool_V_we0_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pool_V_we0 <= ap_const_logic_1;
        else 
            pool_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln15_1_fu_555_p3 <= 
        conv1_V_q2 when (xor_ln1651_fu_549_p2(0) = '1') else 
        select_ln15_fu_535_p3;
    select_ln15_2_fu_575_p3 <= 
        conv1_V_q1 when (xor_ln1651_1_fu_569_p2(0) = '1') else 
        select_ln15_1_fu_555_p3;
    select_ln15_3_fu_595_p3 <= 
        conv1_V_q0 when (xor_ln1651_2_fu_589_p2(0) = '1') else 
        select_ln15_2_fu_575_p3;
    select_ln15_fu_535_p3 <= 
        ap_const_lv16_F600 when (icmp_ln1651_fu_529_p2(0) = '1') else 
        conv1_V_q3;
    select_ln8_10_fu_254_p3 <= 
        ap_const_lv8_1 when (icmp_ln8_fu_224_p2(0) = '1') else 
        add_ln8_2_fu_248_p2;
    select_ln8_1_fu_369_p3 <= 
        ap_const_lv4_0 when (icmp_ln8_reg_694_pp0_iter2_reg(0) = '1') else 
        z_fu_86;
    select_ln8_2_fu_498_p3 <= 
        ap_const_lv8_0 when (icmp_ln8_reg_694_pp0_iter3_reg(0) = '1') else 
        index_1_fu_82;
    select_ln8_3_fu_236_p3 <= 
        add_ln6_1_fu_230_p2 when (icmp_ln8_fu_224_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln8_4_fu_376_p3 <= 
        ap_const_lv11_0 when (icmp_ln8_reg_694_pp0_iter2_reg(0) = '1') else 
        empty_fu_363_p2;
    select_ln8_5_fu_511_p3 <= 
        add_ln8_1_fu_505_p2 when (and_ln8_reg_719_pp0_iter3_reg(0) = '1') else 
        select_ln8_2_fu_498_p3;
    select_ln8_6_fu_305_p3 <= 
        ap_const_lv4_0 when (or_ln8_fu_300_p2(0) = '1') else 
        y_fu_78;
    select_ln8_7_fu_419_p3 <= 
        p_mid1110_fu_413_p2 when (and_ln8_reg_719(0) = '1') else 
        select_ln8_4_fu_376_p3;
        select_ln8_8_cast_fu_426_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln8_7_fu_419_p3),12));

    select_ln8_8_fu_518_p3 <= 
        add_ln8_1_fu_505_p2 when (and_ln8_reg_719_pp0_iter3_reg(0) = '1') else 
        select_ln8_fu_491_p3;
    select_ln8_9_fu_430_p3 <= 
        add_ln8_fu_383_p2 when (and_ln8_reg_719(0) = '1') else 
        select_ln8_1_fu_369_p3;
    select_ln8_fu_491_p3 <= 
        ap_const_lv8_0 when (icmp_ln8_reg_694_pp0_iter3_reg(0) = '1') else 
        index_fu_90;
    tmp_s_fu_313_p3 <= (select_ln8_6_fu_305_p3 & ap_const_lv1_0);
    xor_ln1651_1_fu_569_p2 <= (icmp_ln1651_2_fu_563_p2 xor ap_const_lv1_1);
    xor_ln1651_2_fu_589_p2 <= (icmp_ln1651_3_fu_583_p2 xor ap_const_lv1_1);
    xor_ln1651_fu_549_p2 <= (icmp_ln1651_1_fu_543_p2 xor ap_const_lv1_1);
    xor_ln8_fu_283_p2 <= (icmp_ln8_reg_694_pp0_iter1_reg xor ap_const_lv1_1);
    zext_ln14_1_fu_453_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln13_fu_447_p2),64));
    zext_ln14_2_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln13_1_fu_458_p2),64));
    zext_ln14_3_fu_475_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln13_2_fu_469_p2),64));
    zext_ln14_fu_442_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln13_fu_437_p2),64));
    zext_ln19_fu_619_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_632_p3),64));
end behav;
